from __future__ import annotations

# AUTO-GENERATED HOOK DISPATCHER ENTRYPOINT (ADR-068, #2295).
# Runs every registered matcher shim for this event in ONE process. DO NOT EDIT
# BY HAND; regenerated by build/scripts/generate_dispatcher.py.
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _bootstrap import ensure_plugin_paths  # noqa: E402

_MAX_STDIN_BYTES = 2 * 1024 * 1024
_GATE_EVENTS = ("PreToolUse", "preToolUse")


def _main() -> int:
    try:
        ensure_plugin_paths()
        from hook_dispatch import run_dispatch  # noqa: E402

        event_dir = Path(__file__).resolve().parent
        manifest = json.loads((event_dir / "_manifest.json").read_text(encoding="utf-8"))
        event = manifest.get("event")
        if not isinstance(event, str):
            raise TypeError("manifest field 'event' must be a string")
        shims = manifest["shims"]
        if not isinstance(shims, list):
            raise TypeError("manifest field 'shims' must be a list")
        # mode selects gate (short_circuit, fail-closed) vs observe (run all,
        # never gate). Default to gate when absent so an older manifest fails
        # closed (ADR-066) rather than silently dropping a guard.
        mode = manifest.get("mode", "gate")
        if mode not in ("gate", "observe"):
            raise ValueError(f"manifest field 'mode' must be 'gate' or 'observe', got {mode!r}")
        expected_mode = "gate" if event in _GATE_EVENTS else "observe"
        if mode != expected_mode:
            raise ValueError(
                f"manifest field 'mode' for {event} must be {expected_mode!r}, got {mode!r}"
            )
        short_circuit = mode == "gate"
        # Validate timeout metadata so malformed manifests fail closed. Do not
        # enforce per-shim timeouts inside the dispatcher: Python cannot kill a
        # timed-out thread, and the host already owns this process timeout.
        timeouts = manifest.get("timeouts", {})
        if not isinstance(timeouts, dict):
            raise TypeError("manifest field 'timeouts' must be a dict when present")
        shim_timeouts = {}
        for shim in shims:
            if not isinstance(shim, str):
                raise TypeError("manifest field 'shims' must contain strings")
            if shim not in timeouts:
                continue
            timeout_sec = int(timeouts[shim])
            if timeout_sec <= 0:
                raise ValueError(f"manifest timeout for {shim} must be positive")
            shim_timeouts[shim] = timeout_sec
        raw = sys.stdin.buffer.read(_MAX_STDIN_BYTES + 1)
        if len(raw) > _MAX_STDIN_BYTES:
            raise ValueError(f"stdin exceeds {_MAX_STDIN_BYTES} bytes")
        return run_dispatch(event_dir, shims, raw, shim_timeouts, short_circuit=short_circuit)
    except Exception as exc:  # noqa: BLE001 - generated entrypoint must fail closed
        print(
            f"hook-dispatch-entrypoint: {type(exc).__name__}: {exc}; denying (fail-closed)",
            file=sys.stderr,
        )
        return 2


sys.exit(_main())
