from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git commit*|git ci*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git commit*|git ci*)'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git commit with ADR changes unless adr-review skill was executed.

    Claude Code PreToolUse hook that enforces ADR review before commit.
    Detects ADR file modifications and blocks commit unless the adr-review
    skill ran in the current session.

    Checks:
    1. Command is git commit
    2. Staged changes include ADR files (ADR-*.md)
    3. Session log contains adr-review evidence
    4. Debate log artifact exists in .agents/analysis/

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not commit, no ADR changes, or review done)
        2 = Block (ADR changes without review)
    """


    import json
    import os
    import re
    import subprocess
    import sys
    from datetime import UTC, datetime
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})", file=sys.stderr)
        sys.exit(2)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import (  # noqa: E402
        get_project_directory,
        get_today_session_log,
        is_git_commit_command,
    )
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402

    _ADR_PATTERN = re.compile(r"(?:^|[\\/])ADR-\d+(?:-\w+)*\.md$", re.IGNORECASE)
    _CANONICAL_SOURCE_PATTERN = re.compile(r"SESSION-PROTOCOL\.md$", re.IGNORECASE)

    _REVIEW_PATTERNS = [
        re.compile(r"/adr-review"),
        re.compile(r"adr-review skill"),
        re.compile(r"ADR Review Protocol"),
        re.compile(r"multi-agent consensus.{0,200}\bADR\b", re.DOTALL),
        re.compile(r"\barchitect\b.{0,80}\bplanner\b.{0,80}\bqa\b", re.DOTALL),
    ]

    _AGENTS_DEBATE = ".agents/analysis/"

    _NO_SESSION_LOG_TEMPLATE = """\

    ## BLOCKED: ADR Changes Without Review

    **YOU MUST run /adr-review before committing ADR changes.**

    ### Changes Detected

    {changes_list}

    ### Required Action

    Invoke the adr-review skill for multi-agent consensus:

    ```
    /adr-review [ADR-path]
    ```

    This ensures 6-agent debate before ADR acceptance.

    **Skill**: `.claude/skills/adr-review/SKILL.md`
    """

    _NO_EVIDENCE_TEMPLATE = """\

    ## BLOCKED: ADR Changes Without Review

    **YOU MUST run /adr-review before committing ADR changes.**

    ### Changes Detected

    {changes_list}

    ### Problem

    {reason}. Session log needs evidence of /adr-review execution.

    ### Required Action

    Invoke the adr-review skill for multi-agent consensus:

    ```
    /adr-review [ADR-path]
    ```

    This ensures 6-agent debate before ADR acceptance.

    **Skill**: `.claude/skills/adr-review/SKILL.md`
    **Session Log**: {session_log_name}
    """


    def write_audit_log(message: str) -> None:
        """Write to the hook audit log for infrastructure error visibility."""
        # audit_log_path is __file__-derived + constant filename; no user input.
        try:
            hook_dir = Path(__file__).resolve().parents[1]
            audit_log_path = hook_dir / "audit.log"
            timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S")
            entry = f"[{timestamp}] [ADRReviewGuard] {message}\n"
            with open(audit_log_path, "a", encoding="utf-8") as f:
                f.write(entry)
        except OSError:
            print(
                f"[ADRReviewGuard] CRITICAL: Audit log write failed. Original error: {message}",
                file=sys.stderr,
            )


    def _is_gated_file(path: str) -> bool:
        """Return True if the path is an ADR or canonical source requiring review."""
        return bool(_ADR_PATTERN.search(path) or _CANONICAL_SOURCE_PATTERN.search(path))


    def get_staged_adr_changes() -> list[str]:
        """Get staged files that match ADR or canonical source patterns.

        Raises on git errors to maintain fail-closed posture for security.
        """
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            stderr = result.stderr.strip()
            msg = f"git diff --cached failed with exit code {result.returncode}: {stderr}"
            raise RuntimeError(msg)

        if not result.stdout.strip():
            return []

        return [f for f in result.stdout.strip().splitlines() if _is_gated_file(f)]


    def check_adr_review_evidence(
        session_log_path: Path,
        project_dir: str,
    ) -> dict[str, object]:
        """Check session log and artifacts for ADR review evidence.

        Returns dict with 'complete' (bool) and 'reason' or 'evidence' key.
        """
        try:
            content = session_log_path.read_text(encoding="utf-8")

            matched_pattern = None
            for pattern in _REVIEW_PATTERNS:
                if pattern.search(content):
                    matched_pattern = pattern.pattern
                    break

            if matched_pattern is None:
                return {
                    "complete": False,
                    "reason": "No adr-review evidence in session log",
                }

            analysis_dir = Path(project_dir) / ".agents" / "analysis"
            if not analysis_dir.is_dir():
                return {
                    "complete": False,
                    "reason": (
                        "Session log mentions adr-review, but "
                        f"{_AGENTS_DEBATE} directory does not exist"
                    ),
                }

            debate_logs = list(analysis_dir.glob("*debate*.md"))
            if not debate_logs:
                return {
                    "complete": False,
                    "reason": (
                        "Session log mentions adr-review, but no debate "
                        f"log artifact found in {_AGENTS_DEBATE}"
                    ),
                }

            return {
                "complete": True,
                "evidence": (
                    "ADR review evidence found: matched pattern "
                    f"'{matched_pattern}' and debate log artifact exists"
                ),
            }

        except PermissionError:
            return {
                "complete": False,
                "reason": ("Session log is locked or you lack permissions. Close editors and retry."),
            }
        except FileNotFoundError:
            return {
                "complete": False,
                "reason": ("Session log was deleted after detection. Create a new session log."),
            }
        except (ValueError, OSError) as exc:
            return {
                "complete": False,
                "reason": (f"Error reading session log: {type(exc).__name__} - {exc}"),
            }


    def _read_git_commit_command() -> str | None:
        """Read the gated git-commit command from stdin, or None to allow.

        Returns the command string only when stdin carries a hook payload whose
        ``tool_input.command`` is a git commit. Non-commit and empty payloads
        return ``None`` so the caller allows the tool through (exit 0). Malformed
        JSON raises ``JSONDecodeError`` and is handled by ``main``'s fail-open
        exception handler. Behavior is unchanged from the inlined version; this
        only moves the input-parsing branches out of ``main`` (#2386).
        """
        if sys.stdin.isatty():
            return None
        input_json = sys.stdin.read()
        if not input_json.strip():
            return None
        hook_input = json.loads(input_json)
        tool_input = hook_input.get("tool_input")
        if not isinstance(tool_input, dict):
            return None
        command = tool_input.get("command")
        if not command:
            return None
        if not is_git_commit_command(command):
            return None
        return command


    def _staged_adr_changes_or_block() -> tuple[list[str] | None, int | None]:
        """Return staged ADR changes, or signal a fail-closed block.

        Returns ``(changes, None)`` when the staged diff was read. On any git
        error returns ``(None, 2)`` so the caller blocks the commit rather than
        let an ADR change slip past an unreadable index. The fail-closed posture
        is unchanged from the inlined version (#2386).
        """
        try:
            return get_staged_adr_changes(), None
        except (RuntimeError, FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
            error_msg = f"Staged ADR check failed (fail-closed): {exc}"
            print(error_msg, file=sys.stderr)
            write_audit_log(error_msg)
            return None, 2


    def _evaluate_adr_review(adr_changes: list[str], today: str) -> int:
        """Decide the exit code once ADR changes are confirmed staged.

        Blocks (exit 2) when there is no session log or the session lacks
        adr-review evidence; allows (exit 0) otherwise. Block messages and
        targets are identical to the inlined version (#2386).
        """
        project_dir = get_project_directory()
        sessions_dir = os.path.join(project_dir, ".agents", "sessions")
        session_log = get_today_session_log(sessions_dir, date=today)

        changes_list = "\n".join(adr_changes)

        if session_log is None:
            print(_NO_SESSION_LOG_TEMPLATE.format(changes_list=changes_list))
            print(
                "Session blocked: ADR changes without review",
                file=sys.stderr,
            )
            return 2

        evidence = check_adr_review_evidence(session_log, project_dir)

        if not evidence["complete"]:
            print(
                _NO_EVIDENCE_TEMPLATE.format(
                    changes_list=changes_list,
                    reason=evidence["reason"],
                    session_log_name=session_log.name,
                )
            )
            print(
                "Session blocked: ADR review not completed in session",
                file=sys.stderr,
            )
            return 2

        return 0


    def main() -> int:
        """Main hook entry point. Returns exit code.

        Sergeant: reads the command, checks for staged ADR changes, then defers
        the review decision to ``_evaluate_adr_review``. Each step is a named
        helper so the control flow stays under the complexity gate (#2386).
        """
        if skip_if_consumer_repo("adr-review-guard"):
            return 0
        try:
            today = datetime.now(tz=UTC).strftime("%Y-%m-%d")

            command = _read_git_commit_command()
            if command is None:
                return 0

            adr_changes, block_code = _staged_adr_changes_or_block()
            if block_code is not None:
                return block_code

            if not adr_changes:
                return 0

            return _evaluate_adr_review(adr_changes, today)

        except Exception as exc:
            # Fail-open on infrastructure errors
            error_msg = f"ADR review guard error: {type(exc).__name__} - {exc}"
            print(error_msg, file=sys.stderr)
            write_audit_log(error_msg)
            return 0
    return main()

_shim_dispatch()
