from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git push*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git push*)'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git push when session logs carry placeholder values.

    Thin adapter over :mod:`push_guard_base`. Activates on
    ``.agents/sessions/*.json`` files in the push changeset.

    Schema (compatible with scripts/validate_session_json.py):

    - ``endingCommit``: tolerated absent (investigation-only sessions); the
      literal placeholder ``"pending"`` is rejected.
    - ``protocolCompliance.sessionEnd.markdownLintRun``: required (per the
      canonical session validator). Both ``Complete`` and ``complete`` keys
      are accepted; same for ``Evidence`` and ``evidence``. ``Complete``
      must be ``true``. ``Evidence`` must be a non-empty, non-placeholder
      string; placeholder detection uses the same word-boundary
      CONTRADICTION_PATTERNS regex as the canonical validator. The canonical
      path is the only accepted location: a legacy top-level
      ``markdownLintRun`` block is treated as missing so this guard cannot
      pass logs that ``scripts/validate_session_json.py`` would reject.

    Stricter than canonical (intentional, documented here so the divergence
    is not silent):

    - The canonical validator records a *warning* for "Missing evidence" on
      a complete=true item. This pre-push guard *blocks* on missing or
      non-string evidence so the placeholder problem cannot reach CI in the
      first place.
    - This guard does not validate the optional ``schemaVersion`` field.
      The schema at ``.agents/schemas/session-log.schema.json`` declares it
      but the canonical Python validator does not enforce it; this guard
      matches the canonical validator's enforcement, not the schema text.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (no session-log files in changeset, all fields valid)
        2 = Block (markdownLintRun missing/incomplete, Evidence placeholder,
            endingCommit literal "pending", or malformed JSON)
    """


    import json
    import re
    import sys
    from pathlib import Path

    from _bootstrap import ensure_plugin_paths

    ensure_plugin_paths()

    from push_guard_base import run_guard  # noqa: E402
    from hook_utilities import get_project_directory  # noqa: E402

    GUARD_NAME = "session-log-field"
    GLOBS = [".agents/sessions/*.json"]
    # Placeholder regex is the SAME word-boundary pattern as the canonical
    # scripts/validate_session_json.py CONTRADICTION_PATTERNS, so any string
    # that would trigger the canonical evidence-contradiction warning will
    # trip this guard. Real session logs include short-but-valid evidence
    # such as "0 errors" so no minimum-length floor is enforced.
    #
    # Note on enforcement-strength divergence (kept stricter than canonical
    # on purpose): the canonical validator only records a *warning* when a
    # complete=true item is missing evidence, while this pre-push guard
    # *blocks* missing or non-string evidence. The intent is that placeholder
    # evidence in a session log never reaches CI to begin with; the
    # pre-push guard is the strictest layer in the chain.
    CONTRADICTION_PATTERNS = re.compile(
        r"(?i)\b(not available|skipped|N/A|deferred|will validate|will run|TODO|pending|TBD)\b"
    )


    def _ending_commit_is_placeholder(path: str, data: dict) -> list[str]:
        """Block only the literal 'pending' placeholder.

        Real session schema allows endingCommit to be absent (investigation-only
        sessions, no-commit ends). Empty string and missing key are tolerated;
        only the canonical placeholder string 'pending' is rejected.
        """
        value = data.get("endingCommit")
        if isinstance(value, str) and value == "pending":
            return [f"{path}:endingCommit literal 'pending' placeholder"]
        return []


    def _markdown_lint_run(data: dict) -> dict | None:
        """Locate markdownLintRun at the canonical path.

        Canonical: protocolCompliance.sessionEnd.markdownLintRun.

        The canonical session validator (scripts/validate_session_json.py) reads
        only this path. A previous version of this guard accepted a legacy
        top-level fallback, but that created a gap: a session log with only
        top-level markdownLintRun would pass this pre-push guard yet still fail
        the canonical CI validator. Aligning to the canonical path closes the gap.

        Defensive: a malformed log might set protocolCompliance or sessionEnd
        to a list or string. Treat any non-dict node along the path as missing
        rather than raising AttributeError.
        """
        pc = data.get("protocolCompliance")
        if not isinstance(pc, dict):
            return None
        end = pc.get("sessionEnd")
        if not isinstance(end, dict):
            return None
        canonical = end.get("markdownLintRun")
        if isinstance(canonical, dict):
            return canonical
        return None


    def _read_complete(run: dict) -> object:
        """Tolerate both Complete and complete keys."""
        if "Complete" in run:
            return run["Complete"]
        return run.get("complete")


    def _read_evidence(run: dict) -> object:
        """Tolerate both Evidence and evidence keys."""
        if "Evidence" in run:
            return run["Evidence"]
        return run.get("evidence")


    def _check_markdown_lint_present(path: str, data: dict) -> list[str]:
        """Canonical validator requires markdownLintRun. Missing is a violation."""
        if _markdown_lint_run(data) is None:
            return [
                f"{path}:protocolCompliance.sessionEnd.markdownLintRun missing "
                "(required by scripts/validate_session_json.py)"
            ]
        return []


    def _check_markdown_lint_complete(path: str, data: dict) -> list[str]:
        run = _markdown_lint_run(data)
        if run is None:
            return []
        if _read_complete(run) is not True:
            return [
                f"{path}:protocolCompliance.sessionEnd.markdownLintRun.Complete "
                "must be true"
            ]
        return []


    def _check_markdown_lint_evidence(path: str, data: dict) -> list[str]:
        run = _markdown_lint_run(data)
        if run is None:
            return []
        evidence = _read_evidence(run)
        if not isinstance(evidence, str):
            return [
                f"{path}:protocolCompliance.sessionEnd.markdownLintRun.Evidence "
                "missing or non-string"
            ]
        stripped = evidence.strip()
        if not stripped or CONTRADICTION_PATTERNS.search(stripped):
            return [
                f"{path}:protocolCompliance.sessionEnd.markdownLintRun.Evidence "
                "is a placeholder"
            ]
        return []


    def _validate_one(project_dir: Path, rel_path: str) -> list[str]:
        full = project_dir / rel_path
        try:
            text = full.read_text(encoding="utf-8")
        except (OSError, FileNotFoundError) as exc:
            return [f"{rel_path}: read error - {exc}"]
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            return [f"{rel_path}: JSON parse error - {exc.msg}"]
        if not isinstance(data, dict):
            return [f"{rel_path}: top-level JSON must be an object"]

        violations: list[str] = []
        violations.extend(_ending_commit_is_placeholder(rel_path, data))
        violations.extend(_check_markdown_lint_present(rel_path, data))
        violations.extend(_check_markdown_lint_complete(rel_path, data))
        violations.extend(_check_markdown_lint_evidence(rel_path, data))
        return violations


    def _validate(matching: list[str], _all_changed: list[str]) -> list[str]:
        project_dir = Path(get_project_directory())
        out: list[str] = []
        for rel_path in matching:
            out.extend(_validate_one(project_dir, rel_path))
        return out


    def main() -> int:
        return run_guard(_validate, GLOBS, GUARD_NAME)
    return main()

_shim_dispatch()
