from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(gh pr create*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(gh pr create*)'


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read()
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git commit without session log evidence.

    Claude Code PreToolUse hook that enforces session logging before commits.
    Prevents untracked work by requiring a session log for the current date.

    Checks:
    1. Command is git commit
    2. Session log exists for today in .agents/sessions/
    3. Session log has >= 100 characters and, if JSON, has >= 2 properties

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not commit, or log exists with evidence)
        2 = Block (commit without session log or with empty log)
    """


    import json
    import os
    import sys
    from datetime import UTC, datetime
    from pathlib import Path

    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        # Walk up from this hook looking for .claude-plugin/plugin.json
        # (the plugin manifest marker). The sibling lib/ is the plugin's
        # lib dir. Works regardless of source vs install layout depth;
        # robust to the M5 generator copying this file to a different
        # directory level under src/<provider>/hooks/<event>/.
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print("Plugin lib directory not found", file=sys.stderr)
        sys.exit(2)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import (  # noqa: E402
        get_project_directory,
        get_today_session_log,
        is_session_logged_command,
    )
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402

    MIN_SESSION_LOG_LENGTH = 100
    MIN_JSON_PROPERTIES = 2


    def check_session_log_evidence(session_log_path: Path) -> dict[str, object]:
        """Validate that the session log has substantial content.

        Returns a dict with 'valid' key (bool) and either 'reason' or 'content'.
        """
        try:
            content = session_log_path.read_text(encoding="utf-8")

            if len(content) < MIN_SESSION_LOG_LENGTH:
                return {"valid": False, "reason": "Session log exists but is empty"}

            try:
                data = json.loads(content)
                if isinstance(data, dict) and len(data) < MIN_JSON_PROPERTIES:
                    return {"valid": False, "reason": "Session log lacks required sections"}
            except (json.JSONDecodeError, ValueError):
                pass  # Not JSON is acceptable (could be markdown log)

            preview_length = min(200, len(content))
            return {"valid": True, "content": content[:preview_length]}

        except PermissionError:
            return {
                "valid": False,
                "reason": "Session log is locked or you lack permissions. Close editors and retry.",
            }
        except FileNotFoundError:
            return {
                "valid": False,
                "reason": "Session log was deleted after detection. Create a new session log.",
            }
        except (ValueError, OSError) as exc:
            return {
                "valid": False,
                "reason": f"Error reading session log: {type(exc).__name__} - {exc}",
            }


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        if skip_if_consumer_repo("session-log-guard"):
            return 0
        try:
            today = datetime.now(tz=UTC).strftime("%Y-%m-%d")

            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0
            command = tool_input.get("command")
            if not command:
                return 0

            # M7-T3: this hook is registered under both `Bash(git commit*)` and
            # `Bash(gh pr create*)` matchers. Without recognizing both commands,
            # the pr-creation copy fired its shim correctly but no-opped here.
            if not is_session_logged_command(command):
                return 0

            project_dir = get_project_directory()
            sessions_dir = os.path.join(project_dir, ".agents", "sessions")

            if not os.path.isdir(sessions_dir):
                print(
                    "[SKIP] session-log-guard: .agents/sessions/ not found "
                    "(sessions directory missing)",
                    file=sys.stderr,
                )
                return 0

            session_log = get_today_session_log(sessions_dir, date=today)

            if session_log is None:
                protocol_ref = ""
                protocol_path = Path(project_dir) / ".agents" / "SESSION-PROTOCOL.md"
                if protocol_path.is_file():
                    protocol_ref = "\nSee: `.agents/SESSION-PROTOCOL.md` for full details.\n"

                output = f"""
    ## BLOCKED: No Session Log Found

    **YOU MUST create a session log before committing.**

    ### Why Session Logs Matter
    - Evidence of work performed
    - Compliance tracking (ADR-007, ADR-033)
    - Context for future sessions
    - Audit trail for peer review

    ### How to Create a Session Log

    **Option 1: Use /session-init skill**
    ```
    /session-init
    ```

    **Option 2: Create manually**
    ```
    python3 scripts/sessions/initialize_session_log.py
    ```

    Session logs go in: `.agents/sessions/{today}-session-NN.json`

    **Current Date**: {today}
    **Sessions Directory**: {sessions_dir}
    {protocol_ref}"""
                print(output)
                print("Session blocked: No session log found for today", file=sys.stderr)
                return 2

            evidence = check_session_log_evidence(session_log)

            if not evidence["valid"]:
                reason = evidence["reason"]
                output = f"""
    ## BLOCKED: Session Log Empty or Invalid

    **Reason**: {reason}

    ### Fix

    Edit the session log and add substantial work evidence:

    ```
    {session_log}
    ```

    Session log MUST contain:
    - Timestamp of work
    - Description of tasks performed
    - Tool usage evidence
    - Key decisions made

    **Current Session Log**: {session_log.name}
    """
                print(output)
                print("Session blocked: Session log has insufficient evidence", file=sys.stderr)
                return 2

            return 0

        except Exception as exc:
            # Fail-open on errors (don't block on infrastructure issues)
            print(f"Session log guard error: {type(exc).__name__} - {exc}", file=sys.stderr)
            return 0


    if __name__ == "__main__":
        sys.exit(main())
    return 0

_shim_dispatch()
