from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git push*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git push*)'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git push without retrospective evidence per ADR-033.

    Claude Code PreToolUse hook that enforces retrospective before push.
    Prevents pushing without capturing session learnings.

    Gate triggers on:
    - git push commands

    Evidence requirements (any one satisfies):
    1. Retrospective section in session log (## Retrospective)
    2. Retrospective file in .agents/retrospective/ for today
    3. Reference to retrospective file in session log

    Bypass conditions:
    - Documentation-only changes (no code files)
    - Trivial sessions (<10 minutes, single file)
    - SKIP_RETROSPECTIVE_GATE environment variable set

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not push, or retrospective evidence exists)
        2 = Block (push without retrospective evidence)
    """


    import json
    import os
    import re
    import subprocess
    import sys
    import time
    from datetime import UTC, datetime
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})", file=sys.stderr)
        # Non-blocking hook: exit 0 on bootstrap failure (intentional, not a typo)
        sys.exit(0)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)  # Fail open when lib not found

    try:
        from hook_utilities import get_project_directory, get_today_session_log
    except ImportError:
        # Fallback implementations when hook_utilities is not available
        def get_project_directory() -> str:
            """Resolve the project root directory."""
            env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
            if env_dir:
                return str(Path(env_dir).resolve())
            return str(Path.cwd())

        def get_today_session_log(sessions_dir: str, date: str | None = None) -> Path | None:
            """Find the most recent session log for the given date."""
            if date is None:
                date = datetime.now(tz=UTC).strftime("%Y-%m-%d")
            sessions_path = Path(sessions_dir)
            if not sessions_path.is_dir():
                return None
            try:
                logs = sorted(
                    sessions_path.glob(f"{date}-session-*.json"),
                    key=lambda p: p.stat().st_mtime,
                    reverse=True,
                )
            except OSError:
                return None
            return logs[0] if logs else None


    _GIT_PUSH_PATTERN = re.compile(r"(?:^|\s)git\s+push\b")
    _RETROSPECTIVE_SECTION_PATTERN = re.compile(
        r"(?i)(##\s*retrospective|retrospective\s*section|learnings?\s*captured)"
    )
    _RETROSPECTIVE_FILE_REF_PATTERN = re.compile(
        r"(?i)(\.agents/retrospective/|retrospective[-_]?file|retro[-_]?\d{4})"
    )

    # Documentation-only file patterns
    _DOC_PATTERNS = [
        re.compile(r"\.md$"),
        re.compile(r"\.txt$"),
        re.compile(r"(^|/)README$"),
        re.compile(r"(^|/)LICENSE$"),
        re.compile(r"(^|/)CHANGELOG$"),
        re.compile(r"\.gitignore$"),
        re.compile(r"\.editorconfig$"),
    ]

    _TRIVIAL_SESSION_MINUTES = 10


    def is_git_push_command(command: str | None) -> bool:
        """Check if a command string is a git push command."""
        if not command:
            return False
        return _GIT_PUSH_PATTERN.search(command) is not None


    def check_retrospective_in_session_log(session_log: Path) -> bool:
        """Check if session log contains retrospective evidence."""
        try:
            content = session_log.read_text(encoding="utf-8")
            if _RETROSPECTIVE_SECTION_PATTERN.search(content):
                return True
            if _RETROSPECTIVE_FILE_REF_PATTERN.search(content):
                return True
        except OSError:
            pass
        return False


    def check_retrospective_file_exists(project_dir: str) -> bool:
        """Check if a retrospective file exists for today."""
        retro_dir = Path(project_dir) / ".agents" / "retrospective"
        if not retro_dir.is_dir():
            return False

        today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
        try:
            # Look for files matching today's date
            today_retros = list(retro_dir.glob(f"{today}*.md"))
            return len(today_retros) > 0
        except OSError:
            return False


    def check_documentation_only() -> bool:
        """Check if all changed files are documentation-only."""
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "origin/main...HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                result = subprocess.run(
                    ["git", "diff", "--name-only", "origin/main"],
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                if result.returncode != 0:
                    return False

            changed_files = result.stdout.strip()
            if not changed_files:
                return True  # No changes, allow

            for file_path in changed_files.splitlines():
                is_doc = any(pat.search(file_path) for pat in _DOC_PATTERNS)
                if not is_doc:
                    return False

            return True
        except (subprocess.TimeoutExpired, OSError):
            return False


    def check_trivial_session(session_log: Path | None) -> bool:
        """Check if this is a trivial session (short duration, minimal changes).

        Uses the session log creation time to measure duration. Falls back to
        allowing bypass only when no session log exists (no session started).
        """
        if session_log is None:
            return False

        # Derive elapsed time from session log creation
        try:
            log_ctime = session_log.stat().st_ctime
            elapsed_minutes = (time.time() - log_ctime) / 60
        except OSError:
            return False

        if elapsed_minutes > _TRIVIAL_SESSION_MINUTES:
            return False

        # Check number of changed files
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "origin/main...HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                return False

            changed_files = result.stdout.strip().splitlines()
            # Trivial = single file change
            return len(changed_files) <= 1
        except (subprocess.TimeoutExpired, OSError):
            return False


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0
            command = tool_input.get("command")
            if not command:
                return 0

            if not is_git_push_command(command):
                return 0

            project_dir = get_project_directory()
            sessions_dir = os.path.join(project_dir, ".agents", "sessions")

            # Skip if .agents infrastructure is absent (consumer repo)
            if not os.path.isdir(sessions_dir):
                print(
                    "[SKIP] .agents/sessions/ not found (consumer repo). "
                    "Retrospective enforcement skipped.",
                    file=sys.stderr,
                )
                return 0

            # Bypass 1: Environment variable override
            if os.environ.get("SKIP_RETROSPECTIVE_GATE") == "true":
                print(
                    "Retrospective gate bypassed via SKIP_RETROSPECTIVE_GATE environment variable",
                    file=sys.stderr,
                )
                return 0

            # Resolve session log early (needed by trivial session check)
            today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
            session_log = get_today_session_log(sessions_dir, date=today)

            # Bypass 2: Documentation-only changes
            if check_documentation_only():
                return 0

            # Bypass 3: Trivial session
            if check_trivial_session(session_log):
                return 0

            has_retrospective = False

            # Check 1: Retrospective file exists for today
            if check_retrospective_file_exists(project_dir):
                has_retrospective = True

            # Check 2: Retrospective section in session log
            if session_log and check_retrospective_in_session_log(session_log):
                has_retrospective = True

            if has_retrospective:
                return 0

            # Block: No retrospective evidence found
            output = f"""
    ## BLOCKED: Retrospective Required Before Push

    **Session retrospective required per ADR-033 enforcement gates.**

    ### Why Retrospectives Matter
    - Capture learnings while context is fresh
    - Prevent knowledge loss across sessions
    - Enable continuous improvement
    - Build institutional memory

    ### How to Satisfy This Gate

    **Option 1: Run retrospective agent**
    ```
    Task(subagent_type='retrospective', prompt='Analyze this session for learnings')
    ```

    **Option 2: Add retrospective section to session log**
    Add a `## Retrospective` section to today's session log with:
    - What went well
    - What could improve
    - Key learnings

    **Option 3: Create retrospective file**
    Create `.agents/retrospective/{today}-*.md` with session analysis.

    ### Bypass Conditions
    - Documentation-only changes (auto-detected)
    - Trivial sessions (<10 minutes, single file)
    - Set `SKIP_RETROSPECTIVE_GATE=true` (requires justification)

    **Current Date**: {today}
    **Session Log**: {session_log.name if session_log else "Not found"}
    """
            print(output)
            print("Push blocked: No retrospective evidence found", file=sys.stderr)
            return 2

        except Exception as exc:
            # Fail-open on errors (don't block on infrastructure issues)
            print(
                f"Retrospective gate error: {type(exc).__name__} - {exc}",
                file=sys.stderr,
            )
            return 0
    return main()

_shim_dispatch()
