from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Routing-level enforcement gates for Claude Code per ADR-033.

    Blocks high-stakes actions until validation prerequisites are met.

    Gates:
    - Gate 2: QA Validation Gate - blocks PR creation without QA evidence
    - Gate 3: Critic Review Gate - blocks PR merge without critic validation
    - Gate 4: ADR Existence Gate - blocks feature PR creation without ADR evidence

    QA Evidence is satisfied by:
    1. QA report exists in .agents/qa/ from the last 24 hours
    2. QA section in today's session log

    Critic Evidence is satisfied by:
    1. Critic verdict in today's session log (APPROVED/REJECTED/NEEDS WORK)
    2. Critique file in .agents/critique/ from the last 24 hours

    Bypass conditions (QA):
    - Documentation-only PRs (no code changes)
    - SKIP_QA_GATE environment variable set

    Bypass conditions (Critic):
    - Documentation-only PRs (no code changes)
    - SKIP_CRITIC_GATE environment variable set

    ADR Evidence is satisfied by:
    1. ADR file in .agents/architecture/ modified within the last 7 days
    2. Architect agent section in today's session log

    Bypass conditions (ADR):
    - Non-feature branches (fix/*, docs/*, chore/*, etc.)
    - Documentation-only PRs (no code changes)
    - SKIP_ADR_GATE environment variable set

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Always (uses JSON decision payload for deny/allow semantics)
    """


    import json
    import os
    import re
    import subprocess
    import sys
    import time
    from datetime import UTC, datetime
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})", file=sys.stderr)
        sys.exit(2)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402

    _QA_EVIDENCE_PATTERN = re.compile(r"(?i)## QA|qa agent|Test Results|QA Validation|Test Strategy")
    _CRITIC_EVIDENCE_PATTERN = re.compile(
        r"(?i)critic agent|critic review|APPROVED|REJECTED|NEEDS.?WORK"
    )
    _ADR_EVIDENCE_PATTERN = re.compile(
        r"(?i)architect agent|architecture review|ADR-\d+|architectural decision"
    )

    # Feature branch patterns (require ADR)
    _FEATURE_BRANCH_PATTERN = re.compile(r"^(feat|feature)/")

    # Non-feature branch patterns (bypass ADR gate)
    _NON_FEATURE_BRANCH_PATTERNS = [
        re.compile(r"^(fix|bugfix|hotfix)/"),
        re.compile(r"^(docs|doc)/"),
        re.compile(r"^(chore|ci|build|style|refactor|perf|test)/"),
    ]

    # Documentation-only file patterns (anchored to prevent substring matches)
    _DOC_PATTERNS = [
        re.compile(r"\.md$"),
        re.compile(r"\.txt$"),
        re.compile(r"(^|/)README$"),
        re.compile(r"(^|/)LICENSE$"),
        re.compile(r"(^|/)CHANGELOG$"),
        re.compile(r"\.gitignore$"),
    ]


    def write_audit_log(hook_name: str, message: str) -> None:
        """Write hook failure events to persistent audit log."""
        try:
            script_dir = Path(__file__).resolve().parent
            audit_log_path = script_dir / "audit.log"
            timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S")
            entry = f"[{timestamp}] [{hook_name}] {message}\n"
            with open(audit_log_path, "a", encoding="utf-8") as f:
                f.write(entry)
        except OSError as exc:
            print(f"[{hook_name}] Audit log write failed: {exc}", file=sys.stderr)
            try:
                import tempfile

                temp_path = Path(tempfile.gettempdir()) / "claude-hook-audit.log"
                timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S")
                entry = f"[{timestamp}] [{hook_name}] {message}\n"
                with open(temp_path, "a", encoding="utf-8") as f:
                    f.write(entry)
            except OSError:
                print(
                    f"[{hook_name}] CRITICAL: All audit log paths failed. Original message: {message}",
                    file=sys.stderr,
                )


    def get_today_session_log_local() -> Path | None:
        """Find today's most recent session log.

        Uses local logic instead of the shared utility because this hook
        operates from CWD rather than the project root discovered by the utility.
        """
        session_dir = Path(".agents/sessions")
        today = datetime.now(tz=UTC).strftime("%Y-%m-%d")

        if not session_dir.is_dir():
            print(f"routing_gates: Session directory not found: {session_dir}", file=sys.stderr)
            return None

        try:
            logs = sorted(
                session_dir.glob(f"{today}-session-*.json"),
                key=lambda p: p.name,
                reverse=True,
            )
            return logs[0] if logs else None
        except OSError as exc:
            msg = f"Failed to read session logs from {session_dir}: {exc}"
            print(f"routing_gates: {msg}", file=sys.stderr)
            write_audit_log("RoutingGates", f"Session log read error: {exc}")
            return None


    def check_qa_evidence() -> bool:
        """Check for QA evidence in reports or session log."""
        # Option 1: QA report in .agents/qa/ from last 24 hours
        qa_dir = Path(".agents/qa")
        if qa_dir.is_dir():
            cutoff_time = time.time() - (24 * 3600)
            for report in qa_dir.glob("*.md"):
                if report.stat().st_mtime > cutoff_time:
                    return True

        # Option 2: QA section in session log
        session_log = get_today_session_log_local()
        if session_log is not None:
            try:
                content = session_log.read_text(encoding="utf-8")
            except OSError as exc:
                msg = f"Session log exists but cannot be read: {exc}"
                print(f"routing_gates: {msg}", file=sys.stderr)
                write_audit_log("RoutingGates", f"Session log read failed: {exc}")
                return False

            if content and _QA_EVIDENCE_PATTERN.search(content):
                return True

        return False


    def check_critic_evidence() -> bool:
        """Check for critic review evidence in critique files or session log."""
        # Option 1: Critique file in .agents/critique/ from last 24 hours
        critique_dir = Path(".agents/critique")
        if critique_dir.is_dir():
            cutoff_time = time.time() - (24 * 3600)
            for critique in critique_dir.glob("*.md"):
                if critique.stat().st_mtime > cutoff_time:
                    return True

        # Option 2: Critic verdict in session log
        session_log = get_today_session_log_local()
        if session_log is not None:
            try:
                content = session_log.read_text(encoding="utf-8")
            except OSError as exc:
                msg = f"Session log exists but cannot be read: {exc}"
                print(f"routing_gates: {msg}", file=sys.stderr)
                write_audit_log("RoutingGates", f"Session log read failed: {exc}")
                return False

            if content and _CRITIC_EVIDENCE_PATTERN.search(content):
                return True

        return False


    def get_current_branch() -> str:
        """Get the current git branch name.

        Raises:
            OSError: If git is not found or cannot be executed.
            subprocess.TimeoutExpired: If the command times out.
            subprocess.CalledProcessError: If git returns a non-zero exit code.
            ValueError: If the branch name cannot be determined (e.g., detached HEAD).
        """
        result = subprocess.run(
            ["git", "branch", "--show-current"],
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
        branch = result.stdout.strip()
        if not branch:
            # This can happen in detached HEAD state. Treat as an error for the gate.
            raise ValueError("Failed to get current branch name (e.g., detached HEAD).")
        return branch


    def is_feature_branch(branch: str) -> bool:
        """Check if the branch is a feature branch requiring ADR evidence."""
        if not branch:
            return False
        return bool(_FEATURE_BRANCH_PATTERN.match(branch))


    def check_adr_evidence() -> bool:
        """Check for ADR evidence in architecture files or session log."""
        # Option 1: ADR file in .agents/architecture/ modified within last 7 days
        adr_dir = Path(".agents/architecture")
        if adr_dir.is_dir():
            cutoff_time = time.time() - (7 * 24 * 3600)
            for adr_file in adr_dir.glob("ADR-*.md"):
                try:
                    if adr_file.stat().st_mtime > cutoff_time:
                        return True
                except OSError:
                    continue

        # Option 2: Architect agent section in session log
        session_log = get_today_session_log_local()
        if session_log is not None:
            try:
                content = session_log.read_text(encoding="utf-8")
            except OSError as exc:
                msg = f"Session log exists but cannot be read: {exc}"
                print(f"routing_gates: {msg}", file=sys.stderr)
                write_audit_log("RoutingGates", f"Session log read failed: {exc}")
                return False

            if content and _ADR_EVIDENCE_PATTERN.search(content):
                return True

        return False


    def check_documentation_only() -> bool:
        """Check if all changed files are documentation-only.

        Security: checks committed changes (not working tree) to prevent bypass.
        Fail-closed on git errors to prevent QA bypass.
        """
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "origin/main...HEAD"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0:
                result = subprocess.run(
                    ["git", "diff", "--name-only", "origin/main"],
                    capture_output=True,
                    text=True,
                    timeout=10,
                )
                if result.returncode != 0:
                    error_msg = f"git diff failed (exit {result.returncode}): {result.stderr.strip()}"
                    print(
                        f"routing_gates: {error_msg}. Failing closed (git errors block).",
                        file=sys.stderr,
                    )
                    write_audit_log("RoutingGates", error_msg)
                    return False

            changed_files = result.stdout.strip()
            if not changed_files:
                return True  # No changes, allow (fail-open)

            for file_path in changed_files.splitlines():
                is_doc = any(pat.search(file_path) for pat in _DOC_PATTERNS)
                if not is_doc:
                    return False  # Code file found

            return True  # All files are documentation

        except PermissionError as exc:
            error_msg = f"Permission denied checking git diff: {exc}"
            print(f"routing_gates: {error_msg}. Failing closed (QA required).", file=sys.stderr)
            write_audit_log("RoutingGates", error_msg)
            return False
        except OSError as exc:
            error_msg = f"I/O error checking git diff: {exc}"
            print(f"routing_gates: {error_msg}. Failing closed (QA required).", file=sys.stderr)
            write_audit_log("RoutingGates", error_msg)
            return False
        except Exception as exc:
            error_msg = f"Unexpected error checking changed files: {type(exc).__name__} - {exc}"
            print(f"routing_gates: {error_msg}. Failing closed (QA required).", file=sys.stderr)
            write_audit_log("RoutingGates", error_msg)
            return False


    def is_valid_project_root() -> bool:
        """Validate that CWD is a project root directory."""
        indicators = [".claude/settings.json", ".git"]
        cwd = Path.cwd()
        return any((cwd / indicator).exists() for indicator in indicators)


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        if skip_if_consumer_repo("routing-gates"):
            return 0

        if not is_valid_project_root():
            cwd = Path.cwd()
            print(
                f"routing_gates: CWD '{cwd}' does not appear to be a project root "
                "(missing .claude/settings.json or .git). Failing open.",
                file=sys.stderr,
            )
            return 0

        command = ""
        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            input_data = json.loads(input_json)
            tool_input = input_data.get("tool_input")
            if isinstance(tool_input, dict):
                cmd = tool_input.get("command")
                if isinstance(cmd, str):
                    command = cmd
        except (json.JSONDecodeError, ValueError) as exc:
            print(
                f"routing_gates: Failed to parse input JSON. Error: {exc}. "
                "Assuming empty command and allowing action.",
                file=sys.stderr,
            )
            command = ""

        # Pre-check: graceful degradation when sessions directory is absent
        sessions_dir = Path(".agents/sessions")
        if not sessions_dir.is_dir():
            print(
                "[SKIP] routing-gates: .agents/sessions/ not found "
                "(sessions directory missing)",
                file=sys.stderr,
            )
            return 0

        # Gate 2: QA Validation (for PR creation)
        if "gh pr create" in command:
            qa_bypassed = False
            # Bypass 1: Environment variable override
            if os.environ.get("SKIP_QA_GATE") == "true":
                write_audit_log(
                    "RoutingGates",
                    "QA gate bypassed via SKIP_QA_GATE environment variable",
                )
                qa_bypassed = True

            # Bypass 2: Documentation-only changes
            if not qa_bypassed and check_documentation_only():
                qa_bypassed = True

            # Main check: QA evidence required
            if not qa_bypassed and not check_qa_evidence():
                output = {
                    "decision": "deny",
                    "reason": (
                        "QA VALIDATION GATE: QA evidence required before PR creation.\n\n"
                        "Invoke the QA agent to verify changes:\n"
                        "  #runSubagent with subagentType=qa prompt='Verify changes for PR'\n\n"
                        "Or create a QA report file in .agents/qa/\n\n"
                        "Bypass conditions:\n"
                        "- Documentation-only PRs (auto-detected based on file extensions)\n"
                        "- Set SKIP_QA_GATE=true environment variable (requires justification)"
                    ),
                }
                print(json.dumps(output, separators=(",", ":")))
                return 0  # JSON output with deny decision

        # Gate 3: Critic Review (for PR merge)
        if "gh pr merge" in command:
            # Bypass 1: Environment variable override
            if os.environ.get("SKIP_CRITIC_GATE") == "true":
                write_audit_log(
                    "RoutingGates",
                    "Critic gate bypassed via SKIP_CRITIC_GATE environment variable",
                )
                return 0

            # Bypass 2: Documentation-only changes
            if check_documentation_only():
                return 0

            # Main check: Critic evidence required
            if not check_critic_evidence():
                output = {
                    "decision": "deny",
                    "reason": (
                        "CRITIC REVIEW GATE: Critic validation required before merge.\n\n"
                        "Run: Task(subagent_type='critic', prompt='Validate this PR "
                        "for merge readiness')\n\n"
                        "Expected verdict: APPROVED / REJECTED / NEEDS WORK\n\n"
                        "Or create a critique file in .agents/critique/\n\n"
                        "Bypass conditions:\n"
                        "- Documentation-only PRs (auto-detected based on file extensions)\n"
                        "- Set SKIP_CRITIC_GATE=true environment variable "
                        "(requires justification)"
                    ),
                }
                print(json.dumps(output, separators=(",", ":")))
                return 0  # JSON output with deny decision

        # Gate 4: ADR Existence (for feature PR creation)
        if "gh pr create" in command:
            # Bypass 1: Environment variable override
            if os.environ.get("SKIP_ADR_GATE") == "true":
                write_audit_log(
                    "RoutingGates",
                    "ADR gate bypassed via SKIP_ADR_GATE environment variable",
                )
                return 0

            try:
                # Bypass 2: Non-feature branches
                branch = get_current_branch()
            except Exception as exc:
                # Fail-closed: if we can't determine the branch, block the action
                msg = f"get_current_branch failed: {type(exc).__name__} - {exc}"
                print(f"routing_gates: {msg}", file=sys.stderr)
                output = {
                    "decision": "deny",
                    "reason": (
                        f"ADR EXISTENCE GATE FAILED due to an internal error: "
                        f"{type(exc).__name__}. PR creation blocked as a precaution."
                    ),
                }
                print(json.dumps(output, separators=(",", ":")))
                return 0

            if not is_feature_branch(branch):
                return 0

            # Bypass 3: Documentation-only changes
            if check_documentation_only():
                return 0

            # Main check: ADR evidence required for feature branches
            if not check_adr_evidence():
                output = {
                    "decision": "deny",
                    "reason": (
                        "ADR EXISTENCE GATE: Architecture decision record required "
                        "before creating a feature PR.\n\n"
                        "Feature branch detected: "
                        + branch
                        + "\n\n"
                        "Invoke the architect agent to create an ADR:\n"
                        "  Task(subagent_type='architect', prompt='Create ADR for "
                        "this feature')\n\n"
                        "Or create an ADR file in .agents/architecture/ADR-NNN-*.md\n\n"
                        "Bypass conditions:\n"
                        "- Non-feature branches (fix/*, docs/*, chore/*, etc.)\n"
                        "- Documentation-only PRs (auto-detected)\n"
                        "- Set SKIP_ADR_GATE=true environment variable "
                        "(requires justification)"
                    ),
                }
                print(json.dumps(output, separators=(",", ":")))
                return 0  # JSON output with deny decision

        return 0
    return main()

_shim_dispatch()
