# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git commit*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git commit*)'


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize toolArgs for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("toolArgs"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read()
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git commit/push on main/master branches.

    Claude Code PreToolUse hook that prevents accidental commits and pushes
    to protected branches (main, master). Enforces SESSION-PROTOCOL requirement
    that work must be done on feature branches.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow operation
        2 = Block operation (on protected branch)
    """

    from __future__ import annotations

    import json
    import os
    import subprocess
    import sys

    PROTECTED_BRANCHES = ("main", "master")


    def write_block_response(reason: str) -> None:
        """Write a JSON block response to stdout."""
        response = json.dumps({"decision": "block", "reason": reason})
        print(response)


    def get_working_directory(hook_input: dict[str, object]) -> str:
        """Resolve the working directory from hook input or environment."""
        cwd = hook_input.get("cwd")
        if isinstance(cwd, str) and cwd.strip():
            return cwd.strip()

        env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
        if env_dir:
            return env_dir

        return os.getcwd()


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)
        except (json.JSONDecodeError, ValueError) as exc:
            print(f"branch_protection_guard: Failed to parse input JSON: {exc}", file=sys.stderr)
            return 0

        cwd = get_working_directory(hook_input)

        try:
            result = subprocess.run(
                ["git", "branch", "--show-current"],
                capture_output=True,
                text=True,
                cwd=cwd,
                timeout=10,
            )

            if result.returncode == 128:
                msg = (
                    f"Not a git repository or git not installed in '{cwd}'. "
                    "Cannot verify branch safety. Check: git status"
                )
                print(msg, file=sys.stderr)
                write_block_response(msg)
                return 2

            if result.returncode != 0:
                output = result.stderr.strip() or result.stdout.strip()
                msg = (
                    f"Cannot determine current git branch in '{cwd}' "
                    f"(git failed with exit code {result.returncode}). "
                    f"Verify manually: git branch --show-current. Output: {output}"
                )
                print(msg, file=sys.stderr)
                write_block_response(msg)
                return 2

            current_branch = result.stdout.strip()

            if current_branch in PROTECTED_BRANCHES:
                msg = (
                    f"Cannot commit or push directly to protected branch '{current_branch}'. "
                    "Create a feature branch first: git checkout -b feature/your-feature-name"
                )
                write_block_response(msg)
                return 2

            return 0

        except Exception as exc:
            msg = (
                f"Branch protection check failed in '{cwd}': {exc}. "
                "Verify manually: git branch --show-current."
            )
            print(msg, file=sys.stderr)
            write_block_response(msg)
            return 2


    if __name__ == "__main__":
        sys.exit(main())
    return 0

_shim_dispatch()
