from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git push*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git push*)'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block git push when the open PR description does not match the diff.

    Thin adapter over :mod:`push_guard_base`. Activates whenever the push
    changeset is non-empty (glob ``*``) and runs
    ``scripts/validation/pr_description.py`` in CI mode against the active
    PR. Real CRITICAL mismatches (file mentioned but not in diff) block the
    push. Tooling failures (missing gh, no PR open, timeout, OSError) all
    fail-open so a temporary infrastructure problem never wedges the user.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (clean validator, no PR for branch, gh missing, timeout,
            OSError, or empty changeset)
        2 = Block (validator reported CRITICAL mismatches, or config error)
    """


    import shutil
    import subprocess
    import sys

    from _bootstrap import ensure_plugin_paths

    ensure_plugin_paths()

    from push_guard_base import emit_fail_open, run_guard  # noqa: E402
    from hook_utilities import get_project_directory  # noqa: E402

    GUARD_NAME = "pr-description"
    GLOBS = ["*"]
    GH_TIMEOUT = 10
    VALIDATOR_TIMEOUT = 60
    VALIDATOR_PATH = "scripts/validation/pr_description.py"


    def _discover_pr_number(project_dir: str) -> int | None:
        """Return the PR number for the current branch, or None on any failure.

        Uses ``gh pr view`` against the local HEAD. The fail-open semantics are
        intentional: a brand-new branch with no PR open yet, a missing gh
        binary, or a transient gh failure must NOT block the push. The guard
        only exists to catch mismatches once a PR is open and authored.
        """
        if shutil.which("gh") is None:
            print(
                f"[{GUARD_NAME}] gh CLI not on PATH; allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(GUARD_NAME, "gh_missing", "gh CLI not on PATH")
            return None
        try:
            proc = subprocess.run(
                ["gh", "pr", "view", "--json", "number", "-q", ".number"],
                capture_output=True,
                text=True,
                timeout=GH_TIMEOUT,
                shell=False,
                check=False,
                cwd=project_dir,
            )
        except subprocess.TimeoutExpired:
            print(
                f"[{GUARD_NAME}] gh pr view timed out after {GH_TIMEOUT}s; "
                f"allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(GUARD_NAME, "gh_timeout", f"gh pr view exceeded {GH_TIMEOUT}s")
            return None
        except (FileNotFoundError, OSError) as exc:
            print(
                f"[{GUARD_NAME}] gh pr view failed to invoke: {exc}; "
                f"allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(GUARD_NAME, "gh_oserror", f"{type(exc).__name__}: {exc}")
            return None
        if proc.returncode != 0:
            # Distinguish the common failure modes so on-call can act on the
            # real cause: no-PR-yet, auth, network, or generic.
            stderr_text = (proc.stderr or "").strip()
            stderr_lower = stderr_text.lower()
            first_line = stderr_text.splitlines()[0] if stderr_text else "non-zero exit"
            if "no pull requests found" in stderr_lower or "no commits between" in stderr_lower:
                cause = "no PR found for current branch"
                reason = "no_pr_for_branch"
            elif "authent" in stderr_lower or "not logged" in stderr_lower or "token" in stderr_lower:
                cause = "gh auth failure"
                reason = "gh_auth_failure"
            elif "network" in stderr_lower or "could not resolve" in stderr_lower or "timed out" in stderr_lower:
                cause = "gh network failure"
                reason = "gh_network_failure"
            else:
                cause = "gh pr view failed"
                reason = "gh_nonzero_exit"
            print(
                f"[{GUARD_NAME}] {cause} ({first_line}); allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(GUARD_NAME, reason, f"{cause}: {first_line}")
            return None
        raw = proc.stdout.strip()
        if not raw:
            print(
                f"[{GUARD_NAME}] gh pr view returned empty PR number; "
                f"allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(GUARD_NAME, "gh_empty_output", "gh pr view returned empty PR number")
            return None
        try:
            return int(raw)
        except ValueError:
            print(
                f"[{GUARD_NAME}] gh pr view returned non-numeric PR number "
                f"{raw!r}; allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(GUARD_NAME, "gh_nonnumeric_output", f"PR number was {raw!r}")
            return None


    def _parse_critical_lines(stdout: str) -> list[str]:
        """Extract CRITICAL violation blocks from validator stdout.

        Validator format (see scripts/validation/pr_description.py
        print_results):

            [CRITICAL] <issue_type>
              File: <path>
              <message>

        Each block becomes one violation entry that preserves the file path
        and message so the user can act without rerunning the validator.
        """
        violations: list[str] = []
        lines = stdout.splitlines()
        i = 0
        while i < len(lines):
            line = lines[i]
            if line.startswith("[CRITICAL]"):
                block = [line.rstrip()]
                j = i + 1
                while j < len(lines) and (
                    lines[j].startswith("  ") or lines[j].startswith("\t")
                ):
                    stripped = lines[j].rstrip()
                    if stripped:
                        block.append(stripped)
                    j += 1
                violations.append(" ".join(block))
                i = j
                continue
            i += 1
        return violations


    def _validate(_matching: list[str], _all_changed: list[str]) -> list[str]:
        project_dir = get_project_directory()

        pr_num = _discover_pr_number(project_dir)
        if pr_num is None:
            return []

        try:
            proc = subprocess.run(
                [
                    sys.executable,
                    VALIDATOR_PATH,
                    "--pr-number",
                    str(pr_num),
                    "--ci",
                ],
                capture_output=True,
                text=True,
                timeout=VALIDATOR_TIMEOUT,
                shell=False,
                check=False,
                cwd=project_dir,
            )
        except subprocess.TimeoutExpired:
            print(
                f"[{GUARD_NAME}] {VALIDATOR_PATH} timed out after "
                f"{VALIDATOR_TIMEOUT}s; allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(
                GUARD_NAME,
                "validator_timeout",
                f"{VALIDATOR_PATH} exceeded {VALIDATOR_TIMEOUT}s",
            )
            return []
        except (FileNotFoundError, OSError) as exc:
            print(
                f"[{GUARD_NAME}] {VALIDATOR_PATH} failed to invoke: {exc}; "
                f"allowing push (fail-open)",
                file=sys.stderr,
            )
            emit_fail_open(
                GUARD_NAME,
                "validator_oserror",
                f"{VALIDATOR_PATH} failed to invoke: {type(exc).__name__}: {exc}",
            )
            return []

        if proc.returncode == 0:
            return []

        if proc.returncode == 2:
            stderr_first = (proc.stderr or "").strip().splitlines()
            reason = stderr_first[0] if stderr_first else "config error"
            return [f"{VALIDATOR_PATH}: config error - {reason}"]

        # rc == 1: CRITICAL mismatch
        violations = _parse_critical_lines(proc.stdout)
        if not violations:
            # Validator returned 1 but stdout did not match the [CRITICAL]
            # parse shape. Surface a generic violation rather than fail-open;
            # the user can rerun the validator locally for full output.
            violations = [
                f"{VALIDATOR_PATH} reported critical issues "
                f"(rc=1, see local run for detail)"
            ]
        violations.append(
            f"Update the PR description to mention only files actually in "
            f"the diff (run {VALIDATOR_PATH} --pr-number {pr_num} for details)."
        )
        return violations


    def main() -> int:
        # include_deletions=True: pr_description.py compares the description
        # against the FULL PR diff (including deletions), so this guard must
        # fire on deletion-only pushes too. The validator never reads the
        # listed paths.
        return run_guard(_validate, GLOBS, GUARD_NAME, include_deletions=True)
    return main()

_shim_dispatch()
