from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash'


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read()
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block raw gh commands when validated skill scripts exist.

    Claude Code PreToolUse hook that enforces skills-first mandate by blocking
    raw gh CLI commands when a tested, validated skill script exists for that
    operation.

    Uses two-stage skill discovery:
    1. Exact mapping via hardcoded operation->action table
    2. Fuzzy matching via filesystem scan (fallback)

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not a gh command, or no skill exists)
        2 = Block (skill exists, must use it)
    """


    import json
    import os
    import re
    import sys
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})", file=sys.stderr)
        sys.exit(2)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import get_project_directory  # noqa: E402
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402

    _GH_COMMAND_PATTERN = re.compile(r"\bgh\s+(\w+)\s+(\w+)")

    # Stage 1: Exact mapping of gh operation/action to skill scripts
    SKILL_MAPPINGS: dict[str, dict[str, dict[str, str]]] = {
        "pr": {
            "view": {
                "script": "get_pr_context.py",
                "example": (
                    "python3 .claude/skills/github/scripts/pr/"
                    "get_pr_context.py --pull-request 123"
                ),
            },
            "list": {
                "script": "get_pull_requests.py",
                "example": "python3 .claude/skills/github/scripts/pr/get_pull_requests.py",
            },
            "create": {
                "script": "new_pr.py",
                "example": (
                    "python3 .claude/skills/github/scripts/pr/"
                    'new_pr.py --title "..." --body "..."'
                ),
            },
            "comment": {
                "script": "post_pr_comment_reply.py",
                "example": (
                    "python3 .claude/skills/github/scripts/pr/"
                    'post_pr_comment_reply.py --pull-request 123 --body "..."'
                ),
            },
            "merge": {
                "script": "merge_pr.py",
                "example": "python3 .claude/skills/github/scripts/pr/merge_pr.py --pull-request 123",
            },
            "close": {
                "script": "close_pr.py",
                "example": "python3 .claude/skills/github/scripts/pr/close_pr.py --pull-request 123",
            },
            "checks": {
                "script": "get_pr_checks.py",
                "example": (
                    "python3 .claude/skills/github/scripts/pr/"
                    "get_pr_checks.py --pull-request 123"
                ),
            },
        },
        "issue": {
            "view": {
                "script": "get_issue_context.py",
                "example": (
                    "python3 .claude/skills/github/scripts/issue/"
                    "get_issue_context.py --issue 456"
                ),
            },
            "create": {
                "script": "new_issue.py",
                "example": (
                    "python3 .claude/skills/github/scripts/issue/"
                    'new_issue.py --title "..." --body "..."'
                ),
            },
            "comment": {
                "script": "post_issue_comment.py",
                "example": (
                    "python3 .claude/skills/github/scripts/issue/"
                    'post_issue_comment.py --issue 456 --body "..."'
                ),
            },
            "list": {
                "script": "get_issue_context.py",
                "example": "python3 .claude/skills/github/scripts/issue/get_issue_context.py",
            },
        },
    }


    def parse_gh_command(command: str) -> dict[str, str] | None:
        """Parse a gh command into operation and action components.

        Returns dict with 'operation', 'action', 'full_command' or None.
        """
        if not command:
            return None

        match = _GH_COMMAND_PATTERN.search(command)
        if not match:
            return None

        return {
            "operation": match.group(1),
            "action": match.group(2),
            "full_command": command,
        }


    def find_skill_script(
        operation: str,
        action: str,
        project_dir: str,
    ) -> dict[str, str] | None:
        """Find the matching skill script for a gh operation/action.

        Stage 1: Check exact mapping.
        Stage 2: Fuzzy filesystem search (fallback).
        Returns dict with 'path' and 'example', or None.
        """
        project_path = Path(project_dir)

        # Stage 1: Exact mapping
        op_mappings = SKILL_MAPPINGS.get(operation)
        if op_mappings:
            action_mapping = op_mappings.get(action)
            if action_mapping:
                script_path = (
                    project_path
                    / ".claude"
                    / "skills"
                    / "github"
                    / "scripts"
                    / operation
                    / action_mapping["script"]
                )
                if script_path.is_file():
                    return {"path": str(script_path), "example": action_mapping["example"]}

        # Stage 2: Fuzzy matching
        search_path = project_path / ".claude" / "skills" / "github" / "scripts" / operation
        if not search_path.is_dir():
            return None

        matching_scripts = sorted(search_path.glob(f"*{action}*.py"))
        if not matching_scripts:
            matching_scripts = sorted(search_path.glob(f"*{action}*.ps1"))

        if matching_scripts:
            script = matching_scripts[0]
            relative_path = f".claude/skills/github/scripts/{operation}/{script.name}"
            runner = "python3" if script.suffix == ".py" else "pwsh"
            return {"path": str(script), "example": f"{runner} {relative_path} [parameters]"}

        return None


    def write_block_response(
        blocked_command: str,
        skill_path: str,
        example_usage: str,
        project_dir: str = "",
    ) -> None:
        """Write an educational block response to stdout."""
        agents_ref = ""
        if project_dir:
            agents_path = Path(project_dir) / "AGENTS.md"
            if agents_path.is_file():
                agents_ref = " See: `AGENTS.md > Skill-First Checkpoint`"
        output = (
            "\n## BLOCKED: Raw GitHub Command Detected\n\n"
            "**YOU MUST use the validated skill script "
            "instead of raw `gh` commands.**\n\n"
            "### Blocked Command\n```\n"
            f"{blocked_command}\n```\n\n"
            "### Required Alternative (Copy-Paste Ready)\n"
            f"```bash\n{example_usage}\n```\n\n"
            "**Why Skills Are Mandatory**:\n"
            "- Tested with pytest (100% coverage)\n"
            "- Structured error handling\n"
            "- Consistent output format\n"
            "- Centrally maintained\n"
            "- Raw `gh` commands: None of the above\n\n"
            f"**This is not optional.**{agents_ref}\n"
        )
        print(output)
        print(f"Blocked: Raw gh command detected. Use skill at {skill_path}", file=sys.stderr)


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        if skip_if_consumer_repo("skill-first-guard"):
            return 0

        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0
            command = tool_input.get("command")
            if not command:
                return 0

            gh_command = parse_gh_command(command)
            if gh_command is None:
                return 0

            project_dir = get_project_directory()
            skill = find_skill_script(gh_command["operation"], gh_command["action"], project_dir)

            if skill is None:
                # No skill exists, fail-open (allow new capabilities)
                return 0

            # Skill exists, BLOCK with educational message
            write_block_response(
                gh_command["full_command"], skill["path"], skill["example"], project_dir
            )
            return 2

        except Exception as exc:
            # Fail-open on errors (don't block on infrastructure issues)
            print(f"Skill-first guard error: {type(exc).__name__} - {exc}", file=sys.stderr)
            return 0


    if __name__ == "__main__":
        sys.exit(main())
    return 0

_shim_dispatch()
