from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block false completion claims without verification evidence.

    Claude Code PreToolUse hook that detects when agents claim "done", "fixed",
    etc. in commit messages or PR operations without prior verification evidence
    (test/build runs) in the session log.

    Addresses 44 false completion mentions across 80+ retrospectives.

    Gate triggers on:
    - git commit messages containing completion signals
    - gh pr create commands with completion language
    - gh pr merge commands (inherently completion actions)

    Evidence requirements (any one satisfies):
    1. Test run in session log (pytest, npm test, etc.)
    2. Build verification in session log (tsc --noEmit, etc.)
    3. PR checks verified (gh pr checks)

    Bypass conditions:
    - SKIP_COMPLETION_GATE=true environment variable
    - Documentation-only changes (*.md files only)
    - No session log present (fail-open), unless the completion claim was
      inferred from an unreadable -F / --body-file (fail-closed)
    - Non-commit/non-PR/non-merge commands

    Hook Type: PreToolUse (blocking on match)
    Exit Codes (Claude Hook Semantics):
        0 = Allow (evidence exists or not a completion claim)
        2 = Block (completion claim without verification)

    References:
        - Issue #1703 (lifecycle hook infrastructure)
        - Issue #1673 (false completion)
        - ADR-008 (protocol automation)
    """


    import json
    import os
    import re
    import subprocess
    import sys
    import tempfile
    import time
    from datetime import UTC, datetime, timedelta
    from pathlib import Path

    # --- Standard hook boilerplate ---
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = os.path.join(_plugin_root, "lib")
    else:
        _lib_dir = str(Path(__file__).resolve().parents[2] / "lib")
    if os.path.isdir(_lib_dir) and _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    try:
        from hook_utilities import (
            get_project_directory,
            get_recent_session_log,
            get_today_session_logs,
        )
        from hook_utilities.guards import skip_if_consumer_repo
    except ImportError:

        def get_project_directory() -> str:
            env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
            if env_dir:
                return str(Path(env_dir).resolve())
            return str(Path.cwd())

        def get_today_session_logs(sessions_dir: str) -> list[Path]:
            today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
            sessions_path = Path(sessions_dir)
            if not sessions_path.is_dir():
                return []
            try:
                return list(sessions_path.glob(f"{today}-session-*.json"))
            except OSError:
                return []

        def get_recent_session_log(sessions_dir: str) -> Path | None:
            """Fallback: return newest today or yesterday session log."""
            from datetime import timedelta

            sessions_path = Path(sessions_dir)
            if not sessions_path.is_dir():
                return None
            now = datetime.now(tz=UTC)
            for offset in (0, 1):
                date = (now - timedelta(days=offset)).strftime("%Y-%m-%d")
                try:
                    candidates = list(sessions_path.glob(f"{date}-session-*.json"))
                    if candidates:
                        return max(candidates, key=lambda p: p.stat().st_mtime)
                except OSError:
                    continue
            return None

        def skip_if_consumer_repo(hook_name: str) -> bool:
            agents_path = Path(get_project_directory()) / ".agents"
            if not agents_path.is_dir():
                print(f"[SKIP] {hook_name}: .agents/ not found (consumer repo)", file=sys.stderr)
                return True
            return False


    HOOK_NAME = "false-completion-gate"

    # Per-invocation cache of the resolved worktree root. One ``git rev-parse`` per
    # process is enough; ``_run_git`` can fire several times per invocation and must
    # not spawn a probe each time. A single-element list (not a bare module global
    # mutated via ``global``) is used so the cache survives the build-time shim that
    # indents this module body into a wrapper function: ``_resolve_worktree_root``
    # closes over the list rather than referencing a module-scope name that the
    # wrapper would shadow.
    _worktree_root_cache: list[str] = []


    def _resolve_worktree_root() -> str:
        """Resolve the current worktree root, falling back to the project dir.

        ``CLAUDE_PROJECT_DIR`` (consumed by ``get_project_directory``) points at the
        MAIN checkout even when the agent runs inside a linked worktree, so the
        session dir and staged diff would be read from the wrong tree and the gate
        would block valid commits (issue #2382). ``git rev-parse --show-toplevel``
        run from the current directory returns the worktree the commit is happening
        in. On any git failure (not a repo, git missing, timeout) fall back to
        ``get_project_directory`` so behavior is unchanged outside a worktree.

        The result is cached per process so repeated ``_run_git`` calls do not each
        spawn a probe.
        """
        if _worktree_root_cache:
            return _worktree_root_cache[0]
        _worktree_root_cache.append(_probe_worktree_root())
        return _worktree_root_cache[0]


    def _probe_worktree_root() -> str:
        """Run ``git rev-parse --show-toplevel``; fall back to the project dir."""
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--show-toplevel"],
                capture_output=True,
                text=True,
                check=False,
                timeout=_GIT_TIMEOUT_SECONDS,
            )
        except (OSError, subprocess.TimeoutExpired):
            return get_project_directory()
        if result.returncode == 0:
            top = result.stdout.strip()
            if top:
                return str(Path(top).resolve())
        return get_project_directory()


    # Completion signal patterns in commit messages / PR titles
    COMPLETION_SIGNALS = re.compile(
        r"\b(done|fixed|complete[ds]?|finished|resolved|merged|shipped|closes?\s+#\d+)\b",
        re.IGNORECASE,
    )

    # A heading-style line is a section name, not a completion claim. Section
    # names like "## Completed" or "Finished:" inside a commit body trip the bare
    # word boundaries in COMPLETION_SIGNALS even though no work is being claimed
    # done (issue #2382). A heading line is one whose entire content (after
    # optional markdown ``#``/list ``-``/``*`` markers) is a single word optionally
    # followed by ``:``; real prose claims like "done with implementation" or
    # "completed migration" have trailing words and are NOT stripped.
    _HEADING_LINE = re.compile(r"^[#\-*\s]*\w+:?\s*$")


    def _strip_heading_lines(text: str) -> str:
        """Drop section-heading lines so heading words do not read as claims.

        Removes lines that are bare section names (a single token, optionally a
        markdown heading or list marker, optionally a trailing colon). Prose lines
        that contain a completion word followed by more words survive, so genuine
        completion claims are still detected. Single-line subjects (the common
        ``git commit -m`` case) are returned unchanged unless the subject itself is
        nothing but a heading-style token.
        """
        kept = [line for line in text.splitlines() if not _HEADING_LINE.match(line)]
        return "\n".join(kept)

    # Verification evidence patterns in session logs (command names)
    VERIFICATION_PATTERNS = [
        re.compile(r"pytest", re.IGNORECASE),
        re.compile(r"npm\s+test", re.IGNORECASE),
        re.compile(r"npm\s+run\s+test", re.IGNORECASE),
        re.compile(r"pnpm\s+test", re.IGNORECASE),
        re.compile(r"yarn\s+test", re.IGNORECASE),
        re.compile(r"tsc\s+--noEmit", re.IGNORECASE),
        re.compile(r"dotnet\s+test", re.IGNORECASE),
        re.compile(r"go\s+test", re.IGNORECASE),
        re.compile(r"gh\s+pr\s+checks", re.IGNORECASE),
        re.compile(r"Invoke-Pester", re.IGNORECASE),
        re.compile(r"uv\s+run\s+pytest", re.IGNORECASE),
        re.compile(r"make\s+test", re.IGNORECASE),
    ]

    # Result patterns that indicate SUCCESSFUL test/check execution. A pytest run
    # that ended with failures proves the command ran, but does not prove the work
    # is complete; the gate must reject a completion claim backed only by failing
    # evidence. Patterns here MUST match success signals only. Failure signals
    # (FAILED, "\d+ failed", "checks failed", "exit code: 1") are intentionally
    # excluded; commits claiming completion after a failing run must be blocked.
    VERIFICATION_RESULT_PATTERNS = [
        re.compile(r"\d+\s+passed", re.IGNORECASE),
        re.compile(r"\bPASSED\b"),
        re.compile(r"exit[_ ]code[:\s]+0\b", re.IGNORECASE),
        re.compile(r"exited with 0\b", re.IGNORECASE),
        re.compile(r"✓|✔"),
        re.compile(r"All checks have passed", re.IGNORECASE),
        re.compile(r"checks? passed", re.IGNORECASE),
    ]


    def _read_stdin_json() -> dict | None:
        """Read and parse JSON from stdin (Claude hook input)."""
        if sys.stdin.isatty():
            return None
        try:
            data = sys.stdin.read().strip()
            if not data:
                return None
            return json.loads(data)
        except (json.JSONDecodeError, OSError):
            return None


    def _extract_command(hook_input: dict) -> str:
        """Extract the command string from hook input.

        Defends against malformed input where ``hook_input``, ``tool_input``,
        or ``tool_input["command"]`` is not a string. Returning an empty
        string lets the caller fall through to the no-op path instead of
        raising a ``TypeError`` inside the regex search and being swallowed
        by the top-level fail-open handler.
        """
        if not isinstance(hook_input, dict):
            return ""
        tool_input = hook_input.get("tool_input", {})
        if not isinstance(tool_input, dict):
            return ""
        command = tool_input.get("command", "")
        if not isinstance(command, str):
            return ""
        return command


    def _is_completion_claim(text: str) -> bool:
        """Check if text contains a completion claim, ignoring heading lines.

        Section-heading words (``## Completed``, ``Finished:``) inside a multi-line
        commit message or PR body are not completion claims; stripping them first
        keeps innocuous commits from being blocked (issue #2382).
        """
        return COMPLETION_SIGNALS.search(_strip_heading_lines(text)) is not None


    def _extract_commit_message_file(command: str) -> str | None:
        """Extract the filename from a `git commit -F <file>` command.

        Returns the file path if found, otherwise None.
        """
        match = re.search(r"(?:^|\s)git\s+(?:commit|ci)\s+.*?(?:-F|--file)[=\s]+([^\s]+)", command)
        if match:
            return match.group(1).strip("'\"")
        return None


    def _allowed_temp_roots() -> tuple[Path, ...]:
        """Trusted root directories where absolute message-file paths are allowed.

        ``gh pr create --body-file`` and ``git commit -F`` are commonly invoked with
        paths under ``$TMPDIR`` (or ``/tmp`` on POSIX); refusing those silently
        bypasses the gate. The allowlist mirrors the temp-root set used by
        ``scripts/github_core/validation.py:_candidate_temp_roots`` (consumed by
        ``assert_valid_body_file``), narrowed to read-only inspection here.

        Canonical set (verbatim from ``_candidate_temp_roots``):
            ``os.environ.get("TMPDIR")``, ``tempfile.gettempdir()``, ``/tmp``,
            ``/private/tmp``.

        No intentional divergence: this list MUST stay character-for-character in
        sync with the canonical source so a body file accepted by the upstream
        validator is also accepted by this read-only gate. Like the canonical, we
        filter non-existent roots and deduplicate by resolved string.
        """
        seen: set[str] = set()
        unique: list[Path] = []
        for candidate in (
            os.environ.get("TMPDIR"),
            tempfile.gettempdir(),
            "/tmp",
            "/private/tmp",
        ):
            if not candidate:
                continue
            try:
                resolved = Path(candidate).resolve()
            except (OSError, ValueError):
                continue
            resolved_str = str(resolved)
            if resolved_str not in seen and resolved.exists():
                seen.add(resolved_str)
                unique.append(resolved)
        return tuple(unique)


    def _is_within(candidate: Path, root: Path) -> bool:
        """Return True when ``candidate`` resolves inside ``root``."""
        try:
            candidate.relative_to(root)
            return True
        except ValueError:
            return False


    def _read_commit_message_file(filepath: str) -> str | None:
        """Read the contents of a commit message file.

        Returns the file contents if readable, otherwise None.

        Security: Applies CWE-22 path traversal containment. Relative paths must
        resolve inside the project root. Absolute paths are allowed only when they
        resolve inside the project root or a trusted temp root (``$TMPDIR``,
        ``tempfile.gettempdir()``, ``/tmp``, ``/private/tmp``); anything outside
        those is rejected so callers cannot point the gate at arbitrary filesystem
        locations.
        """
        try:
            project_root = Path(_resolve_worktree_root()).resolve()
            path = Path(filepath)

            if path.is_absolute():
                resolved = path.resolve()
            else:
                resolved = (project_root / path).resolve()

            trusted_roots = (project_root, *_allowed_temp_roots())
            if not any(_is_within(resolved, root) for root in trusted_roots):
                return None

            if resolved.is_file():
                return resolved.read_text(encoding="utf-8", errors="replace")
        except OSError:
            pass
        return None


    def _is_completion_claim_in_message_file(command: str) -> tuple[bool, bool]:
        """Check if a git commit -F file contains completion signals.

        Returns a tuple ``(has_claim, body_unreadable)``.

        ``body_unreadable`` is True when ``-F`` was specified but the file
        could not be read (outside trusted paths or I/O error). Callers use
        that signal to keep the fail-closed contract end-to-end: when the
        body cannot be inspected, the gate cannot fall through to the
        "no session log => allow" branch.
        """
        message_file = _extract_commit_message_file(command)
        if message_file is None:
            return (False, False)
        message_content = _read_commit_message_file(message_file)
        if message_content is None:
            return (True, True)
        return (_is_completion_claim(message_content), False)


    def _extract_pr_body_file(command: str) -> str | None:
        """Extract the filename from a `gh pr create --body-file <file>` command.

        Returns the file path if found, otherwise None.
        """
        match = re.search(r"(?:^|\s)gh\s+pr\s+create\s+.*?(?:--body-file|-F)[=\s]+([^\s]+)", command)
        if match:
            return match.group(1).strip("'\"")
        return None


    def _is_completion_claim_in_pr_body_file(command: str) -> tuple[bool, bool]:
        """Check if a gh pr create --body-file contains completion signals.

        Uses the same path containment as commit message files (CWE-22).
        Returns a tuple ``(has_claim, body_unreadable)`` so callers can keep
        the fail-closed contract end-to-end (see
        ``_is_completion_claim_in_message_file``).
        """
        body_file = _extract_pr_body_file(command)
        if body_file is None:
            return (False, False)
        body_content = _read_commit_message_file(body_file)
        if body_content is None:
            return (True, True)
        return (_is_completion_claim(body_content), False)


    # Per-git-call timeout. The hook's outer timeout in .claude/settings.json
    # is 5s and this hook can issue multiple git calls per invocation
    # (PR-base resolution + log inspection); keep each call well under the
    # outer budget so a single slow git invocation cannot starve the rest.
    _GIT_TIMEOUT_SECONDS = 2

    # Total wall-time budget across all git calls in one hook invocation.
    # Set below the 5s hook timeout in .claude/settings.json so we surface
    # a documented "deadline exceeded" before the harness kills the process.
    # Callers check ``_deadline_exceeded`` between probes and fall through
    # to the staged-diff path instead of stalling.
    _DEADLINE_BUDGET_SECONDS = 4.0


    def _start_deadline() -> float:
        """Return a monotonic deadline timestamp for the current invocation."""
        return time.monotonic() + _DEADLINE_BUDGET_SECONDS


    def _deadline_exceeded(deadline: float | None) -> bool:
        """Return True when the deadline has elapsed.

        A ``None`` deadline means no budget is being enforced (callers that
        do not propagate a deadline keep the original behavior).
        """
        return deadline is not None and time.monotonic() >= deadline


    def _run_git(
        args: list[str], deadline: float | None = None
    ) -> subprocess.CompletedProcess[str] | None:
        """Run a git subcommand bound to the project directory with a timeout.

        Returns ``None`` when git fails to launch, exceeds the per-call timeout,
        or the caller's deadline has elapsed. Callers can choose how to fall
        back instead of stalling the gate.
        """
        if _deadline_exceeded(deadline):
            return None
        project_dir = _resolve_worktree_root()
        try:
            return subprocess.run(
                ["git", "-C", project_dir, *args],
                capture_output=True,
                text=True,
                check=False,
                timeout=_GIT_TIMEOUT_SECONDS,
            )
        except (OSError, subprocess.TimeoutExpired):
            return None


    def _resolve_pr_base_branch(deadline: float | None = None) -> str | None:
        """Discover the base branch a ``gh pr create`` would target.

        Tries ``origin/HEAD`` symbolic ref first, then common default-branch
        names as a fallback. Returns ``None`` if nothing resolves so the
        caller can fall back to staged changes.

        A timeout on the ``symbolic-ref`` probe is treated the same as a
        missing ``origin/HEAD``: continue into the default-branch loop. That
        keeps behavior consistent with a repo that simply lacks the symbolic
        ref. The shared ``deadline`` bounds the total time across all probes,
        so a failing remote cannot stall the gate even with the loop in play.

        Note: We intentionally skip ``@{u}`` (upstream tracking) because after
        ``git push -u origin feature-branch``, it resolves to ``origin/feature-branch``,
        which is the push target, not the PR merge target (e.g., ``main``).
        """

        head_ref = _run_git(["symbolic-ref", "refs/remotes/origin/HEAD"], deadline)
        if head_ref is not None and head_ref.returncode == 0:
            ref = head_ref.stdout.strip()
            if ref:
                return ref.removeprefix("refs/remotes/")

        for default_branch in ("origin/main", "origin/master", "origin/develop",
                               "main", "master", "develop"):
            if _deadline_exceeded(deadline):
                return None
            rev = _run_git(["rev-parse", "--verify", "--quiet", default_branch], deadline)
            if rev is None:
                continue
            if rev.returncode == 0:
                return default_branch
        return None


    def _changed_files_for_pr(
        current_branch: str, deadline: float | None = None
    ) -> list[str] | None:
        """Return files changed against the resolved PR base, or None if unresolved.

        When the user is already on the default branch the merge-base degenerates
        to HEAD and produces an empty diff, which would falsely classify normal
        changes as non-documentation-only. The caller treats ``None`` as
        "fall through to staged diff."
        """
        base_branch = _resolve_pr_base_branch(deadline)
        if base_branch is None:
            return None

        # If we are sitting on the same ref as the resolved base, skip the
        # merge-base dance: comparing main..HEAD on main returns nothing.
        base_short = base_branch.removeprefix("origin/")
        if current_branch and current_branch == base_short:
            return None

        merge_base = _run_git(["merge-base", base_branch, "HEAD"], deadline)
        if not merge_base or merge_base.returncode != 0:
            return None

        diff = _run_git(
            ["diff", "--name-only", merge_base.stdout.strip(), "HEAD"], deadline
        )
        if not diff or diff.returncode != 0:
            return None
        return [f.strip() for f in diff.stdout.strip().split("\n") if f.strip()]


    def _is_documentation_only(is_branch_operation: bool) -> bool:
        """Check if the relevant changed files are documentation-only.

        For ``git commit`` we look at the index. For ``gh pr create`` and
        ``gh pr merge`` we resolve the actual base branch (upstream /
        origin/HEAD / common defaults) and diff the branch against the
        merge base. If no base can be resolved we fall back to the staged
        diff so docs-only PRs keep their bypass when possible.
        """
        deadline = _start_deadline()
        if is_branch_operation:
            head_branch_result = _run_git(["rev-parse", "--abbrev-ref", "HEAD"], deadline)
            if head_branch_result is None or head_branch_result.returncode != 0:
                return False
            current_branch = head_branch_result.stdout.strip()

            files = _changed_files_for_pr(current_branch, deadline)
            if files is None:
                staged = _run_git(["diff", "--cached", "--name-only"], deadline)
                if staged is None or staged.returncode != 0:
                    return False
                files = [f.strip() for f in staged.stdout.strip().split("\n") if f.strip()]
        else:
            staged = _run_git(["diff", "--cached", "--name-only"], deadline)
            if staged is None or staged.returncode != 0:
                return False
            files = [f.strip() for f in staged.stdout.strip().split("\n") if f.strip()]

        if not files:
            return False
        return all(f.endswith(".md") for f in files)


    def _has_verification_evidence_in_log(
        session_log: Path, found_command: bool, found_result: bool
    ) -> tuple[bool, bool]:
        """Check session log for test/build verification evidence.

        Requires both a command pattern (e.g., "pytest", "npm test") AND a result
        pattern (e.g., "5 passed", "FAILED") to prevent narrative mentions like
        "need to run pytest" from satisfying the gate.

        Streams the log line-by-line. Memory cost is O(1) regardless of log size.

        Args:
            session_log: Path to the session log file. Caller must ensure
                this is not None.
            found_command: Whether a command pattern was already found in a
                previous log (for aggregation across multiple logs).
            found_result: Whether a result pattern was already found in a
                previous log (for aggregation across multiple logs).

        Returns:
            Tuple of (found_command, found_result) after scanning this log.
        """
        try:
            with session_log.open(encoding="utf-8", errors="replace") as handle:
                for line in handle:
                    if not found_command:
                        for pattern in VERIFICATION_PATTERNS:
                            if pattern.search(line):
                                found_command = True
                                break
                    if not found_result:
                        for pattern in VERIFICATION_RESULT_PATTERNS:
                            if pattern.search(line):
                                found_result = True
                                break
                    if found_command and found_result:
                        return (found_command, found_result)
        except OSError:
            pass
        return (found_command, found_result)


    def _has_verification_evidence_across_logs(session_logs: list[Path]) -> bool:
        """Check multiple session logs for test/build verification evidence.

        Aggregates evidence across all logs: a command pattern in one log and
        a result pattern in another log satisfies the gate. This handles cases
        where verification output is split across multiple same-day session files.

        Args:
            session_logs: List of session log paths to check.

        Returns:
            True if both command and result patterns were found across all logs.
        """
        found_command = False
        found_result = False
        for session_log in session_logs:
            found_command, found_result = _has_verification_evidence_in_log(
                session_log, found_command, found_result
            )
            if found_command and found_result:
                return True
        return False


    def _write_audit_log(project_dir: str, command: str, decision: str, reason: str) -> None:
        """Write audit entry for false completion gate decisions."""
        try:
            audit_dir = Path(project_dir) / ".agents" / ".hook-state"
            audit_dir.mkdir(parents=True, exist_ok=True)

            today = datetime.now(tz=UTC).strftime("%Y-%m-%d")
            timestamp = datetime.now(tz=UTC).isoformat()
            audit_file = audit_dir / f"false-completion-gate-{today}.log"

            # Truncate command for audit (avoid huge log entries)
            cmd_preview = command[:200] + "..." if len(command) > 200 else command

            with audit_file.open("a", encoding="utf-8") as f:
                f.write(f"[{timestamp}] {decision}: {reason} | cmd: {cmd_preview}\n")
        except OSError:
            pass


    def main() -> None:
        """Check for false completion claims without verification."""
        # Read stdin first to ensure it's drained before any early exit,
        # maintaining the fail-open drain contract with the harness.
        hook_input = _read_stdin_json()

        if skip_if_consumer_repo(HOOK_NAME):
            sys.exit(0)

        # Bypass via environment variable
        if os.environ.get("SKIP_COMPLETION_GATE", "").lower() == "true":
            sys.exit(0)

        if hook_input is None:
            sys.exit(0)

        command = _extract_command(hook_input)
        if not command:
            sys.exit(0)

        # Only gate on `git commit`/`git ci`, `gh pr create`, and `gh pr merge` commands.
        # The trailing boundary keeps neighbours like `git commit-tree` or
        # `gh pr create-checkout` from accidentally matching.
        is_commit = re.search(r"(?:^|\s)git\s+(commit|ci)(?:\s|$)", command)
        is_pr_create = re.search(r"(?:^|\s)gh\s+pr\s+create(?:\s|$)", command)
        is_pr_merge = re.search(r"(?:^|\s)gh\s+pr\s+merge(?:\s|$)", command)
        if not is_commit and not is_pr_create and not is_pr_merge:
            sys.exit(0)

        # Check if the command/message contains completion signals.
        # For `git commit -F <file>`, also check the message file contents.
        # For `gh pr create --body-file <file>`, also check the body file contents.
        # `gh pr merge` is always treated as a completion claim since merging is
        # an inherent "done" action that requires verification evidence.
        msg_claim, msg_unreadable = _is_completion_claim_in_message_file(command)
        body_claim, body_unreadable = _is_completion_claim_in_pr_body_file(command)
        has_completion_claim = (
            _is_completion_claim(command) or msg_claim or body_claim or bool(is_pr_merge)
        )
        if not has_completion_claim:
            sys.exit(0)

        # ``body_inferred`` is true when the completion claim was inferred from
        # a body file that could not be read (commit -F / pr create --body-file
        # pointing outside trusted paths). The fail-closed contract on those
        # helpers must propagate: when we cannot read the body, we cannot fall
        # through to the "no session log => allow" branch below.
        body_inferred = msg_unreadable or body_unreadable

        # Resolve the CURRENT worktree, not the MAIN checkout. In a linked
        # worktree ``CLAUDE_PROJECT_DIR`` points at main, so the session dir and
        # staged diff must come from ``git rev-parse --show-toplevel`` instead
        # (issue #2382).
        project_dir = _resolve_worktree_root()

        # Bypass for documentation-only changes
        if _is_documentation_only(is_branch_operation=bool(is_pr_create or is_pr_merge)):
            _write_audit_log(project_dir, command, "ALLOW", "documentation-only changes")
            sys.exit(0)

        # Check for verification evidence in session logs from today first.
        # Only fall back to yesterday's logs when today's logs lack evidence,
        # to prevent stale verification from a prior day from satisfying a
        # fresh session's claim.
        sessions_dir = str(Path(project_dir) / ".agents" / "sessions")
        session_logs = get_today_session_logs(sessions_dir)

        # Fail-open when no session logs exist, EXCEPT when the completion
        # claim was inferred from an unreadable body file. In that case we
        # honor the fail-closed contract on the body-file helpers and require
        # verification before allowing the command through.
        if not session_logs and not body_inferred:
            # No today logs: check yesterday (cross-midnight continuation).
            sessions_path = Path(sessions_dir)
            if sessions_path.is_dir():
                yesterday = (datetime.now(tz=UTC) - timedelta(days=1)).strftime("%Y-%m-%d")
                try:
                    yesterday_logs = list(sessions_path.glob(f"{yesterday}-session-*.json"))
                    if yesterday_logs:
                        if _has_verification_evidence_across_logs(yesterday_logs):
                            _write_audit_log(project_dir, command, "ALLOW", "verification evidence found (yesterday)")
                            sys.exit(0)
                        # Yesterday logs exist but lack evidence; fall through to block.
                    else:
                        # No yesterday logs either; fail-open.
                        _write_audit_log(project_dir, command, "ALLOW", "no session log (fail-open)")
                        sys.exit(0)
                except OSError:
                    # Can't read yesterday logs; fail-open.
                    _write_audit_log(project_dir, command, "ALLOW", "no session log (fail-open)")
                    sys.exit(0)
            else:
                # No sessions directory; fail-open.
                _write_audit_log(project_dir, command, "ALLOW", "no session log (fail-open)")
                sys.exit(0)
        elif session_logs:
            # Today's logs exist (a fresh session started today): verification
            # MUST come from today. Stale evidence from a prior day cannot satisfy
            # a fresh session's claim. No yesterday fallback in this branch;
            # cross-midnight continuation is only meaningful when today has no
            # session log at all (the no-today-logs branch above).
            if _has_verification_evidence_across_logs(session_logs):
                _write_audit_log(project_dir, command, "ALLOW", "verification evidence found")
                sys.exit(0)
            # Fall through to block.

        # Block: completion claim without verification
        _write_audit_log(project_dir, command, "BLOCK", "completion claim without verification")

        block_response = json.dumps({
            "decision": "block",
            "reason": (
                "⛔ FALSE COMPLETION GATE: You claimed completion "
                "(done/fixed/complete/etc.) but no verification evidence "
                "(test run, build check, PR checks) was found in the session log. "
                "Run tests or build verification before claiming completion."
            ),
        })
        print(block_response)
        sys.exit(2)
    try:
        return main()
    except Exception as _exc:
        sys.stderr.write('[WARNING] hook error (fail-open): ' + str(_exc) + '\n')
        return 0

_shim_dispatch()
