from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Block bash grep-family symbol searches when an LSP can navigate the target.

    Claude Code PreToolUse hook (matcher: Bash) for ADR-062 conditional LSP-first
    enforcement. It ports the kit's ``bash-grep-block.js`` engine to this repo's
    shared LSP-gate library (``hook_utilities.lsp_symbols`` /
    ``hook_utilities.lsp_provider``). The guard is a no-op (exit 0, no message)
    unless every condition below holds, so enforcement is the exception, not the
    default (ADR-062 Section 2):

        BLOCK iff:
            grep-family search (bash grep/rg/egrep/fgrep/ag/ack)
            AND not ``git grep``         (history search, always allowed)
            AND the extracted pattern contains a code symbol
                (camelCase / PascalCase / dotted / snake>=9)
            AND the target file type has SYMBOL-NAVIGATION capability
                (go-to-definition / find-references: programming languages only)
            AND an LSP tier (Serena or native LSP) is available for that file type
        Else: ALLOW (exit 0).

    Canonical kit ``bash-grep-block.js`` contract, quoted character-for-character
    (canonical-source-mirror.md). The load-bearing patterns are owned by the shared
    ``hook_utilities.lsp_symbols`` module and quoted there; the lines this guard
    depends on directly are (``bash-grep-block.js:21, 27-28``):

        if (data.tool_name !== 'Bash') process.exit(0);
        if (!/\\b(grep|rg|ag|ack)\\b/i.test(cmd)) process.exit(0);
        if (/\\bgit\\s+grep\\b/i.test(cmd)) process.exit(0);

    Stricter/looser/different than canonical
    ----------------------------------------
    - STRICTER blocked set: the kit gates ``grep|rg|ag|ack``. ADR-062 Implementation
      Notes bind the set to ``grep, rg, egrep, fgrep, ag, ack`` (git grep always
      allowed). The extra ``egrep|fgrep`` live in ``lsp_symbols.is_grep_search``.
    - DIFFERENT (CONDITIONAL) blocking: the kit blocks unconditionally on any code
      symbol. This guard additionally requires that the grep target is a
      SYMBOL-NAVIGATION file type AND that an LSP provider is actually available for
      it (ADR-062 Section 2). On a non-code grep target, an out-of-repo target, or
      when no provider is configured, this guard ALLOWS (fail-open). The kit's
      hard-coded path/extension allowlists (``supabase/migrations``, ``node_modules``,
      Tailwind ``--include`` denylist) are replaced by the repo's capability +
      availability model; their intent (do not gate non-code searches) is preserved.
    - DIFFERENT message surface: the kit emits a JSON ``structuredBlockResponse`` and
      ANSI-decorated stderr. This guard follows the repo hook convention
      (``invoke_skill_first_guard.py``): a markdown block to stdout and a single
      structured one-line note to stderr. No secrets are logged (only the matched
      binary class and the symbol tokens, which are agent-supplied search terms).
    - ADDED ``LSP_GATE_MODE``: ``warn`` emits the same guidance as an exit-0 stdout
      advisory (never blocks); ``block`` (default) returns exit 2 (ADR-062 Sec 6).
      ``SKIP_LSP_GATE=true`` bypasses the guard entirely (kill switch).

    Hook Type: PreToolUse (matcher: Bash)
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (not a gated grep, fail-open, warn mode, or kill switch)
        2 = Block (gated grep on a navigable target with an available LSP)
    """


    import json
    import os
    import re
    import sys
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(
            f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        # Fail-open: a navigation guard must never wedge a turn on bootstrap failure.
        sys.exit(0)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import get_project_directory  # noqa: E402
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402
    from hook_utilities.lsp_provider import (  # noqa: E402
        SYMBOL_NAVIGATION,
        detect_providers,
        is_code_target,
        repo_has_programming_provider,
    )
    from hook_utilities.lsp_symbols import (  # noqa: E402
        extract_pattern_and_target,
        is_code_symbol,
        is_git_grep,
        is_grep_search,
    )

    # File-like tokens in a grep command: a dotted path segment ending in a known
    # extension. Used to find a candidate navigable target without a shell parse.
    # Extensions are anchored at a word boundary so ``foo.pyc`` does not match ``.py``.
    _FILE_TOKEN = re.compile(
        r"[\w./\\-]+\.(?:py|ts|tsx|js|jsx|mjs|cjs|sh|ps1|psm1|go|rs|java|kt|swift|"
        r"vue|svelte|cpp|c|h|hpp|md|json|ya?ml|toml)\b(?!\.\w)",
        re.IGNORECASE,
    )

    # `--include=GLOB` / `--include GLOB` extension hints (rg/grep file filters).
    _INCLUDE_GLOB = re.compile(r"--include[= ]\S*?(\.\w+)\b", re.IGNORECASE)

    # Recursive-scan flags for grep (`grep -r`, `-R`, `--recursive`). When present,
    # a grep with no explicit file target scans a directory tree, not stdin.
    _RECURSIVE_FLAG = re.compile(r"(?:^|\s)(?:-[a-zA-Z]*[rR][a-zA-Z]*\b|--recursive\b)")

    # Grep-family binaries that default to recursively scanning the working tree
    # even with no path argument (ripgrep, the silver searcher, ack). For these a
    # bare ``rg Symbol`` is a repo-wide search.
    _DEFAULT_RECURSIVE_BINARY = re.compile(r"\b(?:rg|ag|ack)\b", re.IGNORECASE)

    # Sentinel target reported when the gated scope is a directory / the whole repo
    # rather than a single navigable file. Used only in the guidance message.
    _REPO_SCOPE_TARGET = "<repo>"

    _VALUE_FLAGS = {
        "-A",
        "-B",
        "-C",
        "-m",
        "--after-context",
        "--before-context",
        "--context",
        "--max-count",
    }
    _PATTERN_VALUE_FLAGS = {"-e", "-f", "--file", "--regexp"}

    _BLOCK_HEADER = "## BLOCKED: grep symbol search has an LSP-first alternative"


    def _grep_segment(command: str) -> str:
        """Return the pipe segment that contains the grep-family invocation.

        For piped commands like ``python script.py | grep Symbol``, only the segment
        containing the grep command is grep's actual target scope; files named before
        the pipe are arguments to other commands. The first grep-bearing segment is
        returned; an unpiped command is returned unchanged.
        """
        if "|" not in command:
            return command
        for seg in command.split("|"):
            if is_grep_search(seg):
                return seg
        return command


    def _is_directory_scope(command: str, project_dir: str) -> bool:
        """True if the grep scans an in-repo directory tree, not named files / stdin.

        A repo-wide or recursive grep names no navigable file extension, so the
        per-target check allows it. This detects that scope so the caller can fall
        back to the repo-level provider probe, while preserving the out-of-repo
        fail-open contract.

        A directory argument decides the scope when present: ``grep -r Sym src/`` is
        in-repo, ``grep -r Sym /tmp`` is out-of-repo (allow). With no directory
        argument, a recursive flag (``-r`` / ``-R`` / ``--recursive``) or a
        default-recursive binary (``rg`` / ``ag`` / ``ack``) scans the working tree,
        which is the repo, so it is in-repo. A plain ``grep Foo`` with neither reads
        stdin (for example ``echo x | grep Foo``) and is NOT a directory scope.
        """
        segment = _grep_segment(command)
        dir_args = _directory_arguments(segment)
        if dir_args:
            # An explicit directory argument fixes the scope. Gate only when at
            # least one named directory resolves inside the repo.
            for arg in dir_args:
                resolved = _resolve_in_repo(arg, project_dir)
                if resolved is not None and resolved.is_dir():
                    return True
            return False
        # No directory argument: a recursive flag or default-recursive binary scans
        # the working tree (the repo).
        if _RECURSIVE_FLAG.search(segment):
            return True
        return bool(_DEFAULT_RECURSIVE_BINARY.search(segment))


    def _directory_arguments(segment: str) -> list[str]:
        """Return directory-argument tokens in a grep segment, in order.

        Scans whitespace-delimited tokens after the grep token, skipping option
        flags. The first non-flag token is the pattern; every later non-flag token
        is an explicit path argument. Bare relative file and directory names are
        retained so file targets do not fall back to repo-wide recursion.
        """
        tokens = segment.split()
        seen_grep = False
        seen_pattern = False
        skip_value = False
        value_is_pattern = False
        dirs: list[str] = []
        for token in tokens:
            if not seen_grep:
                if is_grep_search(token):
                    seen_grep = True
                continue
            if skip_value:
                if value_is_pattern:
                    seen_pattern = True
                skip_value = False
                value_is_pattern = False
                continue
            if token in _VALUE_FLAGS or token in _PATTERN_VALUE_FLAGS:
                skip_value = True
                value_is_pattern = token in _PATTERN_VALUE_FLAGS
                continue
            if token.startswith("-"):
                continue
            if not seen_pattern:
                seen_pattern = True
                continue
            dirs.append(token)
        return dirs


    def _candidate_targets(command: str) -> list[str]:
        """Extract candidate file targets from a grep command.

        Returns dotted file tokens and ``--include`` glob extensions found in the
        grep segment (after any pipe), in first-seen order with no duplicates. The
        result drives the capability + availability check. An empty list means the
        command names no file target (for example a piped ``echo x | grep Foo``),
        so the caller must decide whether it is stdin (allow) or directory scope
        (repo-level provider probe).

        For piped commands like ``python script.py | grep Symbol``, only the segment
        containing the grep command is scanned to avoid matching files that are
        arguments to commands before the pipe (which are not grep's targets).
        """
        grep_segment = _grep_segment(command)

        targets: list[str] = []
        seen: set[str] = set()
        for match in _FILE_TOKEN.finditer(grep_segment):
            token = match.group(0)
            if token not in seen:
                seen.add(token)
                targets.append(token)
        for match in _INCLUDE_GLOB.finditer(grep_segment):
            token = f"x{match.group(1)}"
            if token not in seen:
                seen.add(token)
                targets.append(token)
        return targets


    def _resolve_in_repo(target: str, project_dir: str) -> Path | None:
        """Resolve ``target`` under the repo root, or None if it escapes the repo.

        Out-of-repo targets must never be gated; returning None keeps the fail-open
        contract even when the target has a navigable extension and a provider
        exists. Resolution failures also return None (fail-open).
        """
        try:
            repo_root = Path(project_dir).resolve()
            candidate = Path(target)
            resolved = (
                candidate.resolve(strict=False)
                if candidate.is_absolute()
                else (repo_root / candidate).resolve(strict=False)
            )
        except (OSError, ValueError):
            return None
        if not resolved.is_relative_to(repo_root):
            return None
        return resolved


    def _navigable_target_with_provider(
        targets: list[str], project_dir: str
    ) -> str | None:
        """Return the first target that is symbol-navigable AND has an LSP provider.

        A target qualifies only when ``is_code_target`` reports SYMBOL_NAVIGATION
        capability for it AND ``detect_providers`` finds at least one available
        provider (Serena or native LSP) for that file type. Returns None when no
        target qualifies, which the guard treats as fail-open.
        """
        for target in targets:
            resolved = _resolve_in_repo(target, project_dir)
            if resolved is None:
                continue
            if not is_code_target(target, SYMBOL_NAVIGATION):
                continue
            if detect_providers(target, SYMBOL_NAVIGATION, project_dir):
                return target
        return None


    def evaluate_command(command: str, project_dir: str) -> dict | None:
        """Decide whether a bash command is a gated grep symbol search.

        Returns a decision dict ``{"symbols": [...], "target": str}`` when the
        command should be gated, or None to allow (fail-open). Performs provider
        configuration reads, and for repo-wide scope a bounded filesystem scan.
        """
        if not command or not isinstance(command, str):
            return None
        if not is_grep_search(command):
            return None
        if is_git_grep(command):
            return None

        parts, _cleaned = extract_pattern_and_target(command)
        symbols = [p for p in parts if is_code_symbol(p)]
        if not symbols:
            return None

        targets = _candidate_targets(command)
        target = _navigable_target_with_provider(targets, project_dir)
        if target is not None:
            return {"symbols": symbols, "target": target}

        # No explicit navigable file target. A recursive / directory-scoped grep
        # (``grep -r Sym .``, ``rg Sym``) still scans navigable code repo-wide, so
        # gate it when the repo has an active programming-language provider. A
        # provider-less repo, or a plain stdin grep, stays fail-open.
        if _is_directory_scope(command, project_dir) and repo_has_programming_provider(
            project_dir
        ):
            return {"symbols": symbols, "target": _REPO_SCOPE_TARGET}

        return None


    def build_guidance(symbols: list[str], target: str) -> str:
        """Build the LSP-first guidance block (shared by block and warn modes)."""
        symbol_list = ", ".join(symbols)
        if target == _REPO_SCOPE_TARGET:
            scope_line = (
                "Target scope (repository-wide) has programming-language files an "
                "LSP navigates directly."
            )
        else:
            scope_line = (
                f"Target file type ({Path(target).suffix}) has an LSP that navigates "
                "symbols directly."
            )
        return (
            f"\n{_BLOCK_HEADER}\n\n"
            f"Grep searched for code symbol(s): {symbol_list}\n"
            f"{scope_line}\n\n"
            "### Use LSP-first navigation\n"
            "- Definition: `mcp__serena__find_symbol` (or the native `LSP` "
            "go-to-definition)\n"
            "- References: `mcp__serena__find_referencing_symbols` (or native LSP "
            "find-references)\n"
            "- Overview: `mcp__serena__get_symbols_overview` on the file first\n\n"
            "Grep returns noisy matches and forces several wrong Reads; one LSP "
            "query answers with a file:line result.\n\n"
            "Bypass: set `LSP_GATE_MODE=warn` for advisory-only, or "
            "`SKIP_LSP_GATE=true` to disable the gate.\n"
        )


    def _warn_mode() -> bool:
        """True when LSP_GATE_MODE selects advisory (warn) mode instead of block."""
        return os.environ.get("LSP_GATE_MODE", "block").strip().lower() == "warn"


    def _bypassed() -> bool:
        """Allow without evaluating: consumer repo or the SKIP_LSP_GATE kill switch (ADR-062)."""
        if skip_if_consumer_repo("lsp-bash-grep-guard"):
            return True
        if os.environ.get("SKIP_LSP_GATE", "").strip().lower() == "true":
            return True
        return False


    def main() -> int:
        """Main hook entry point. Returns exit code (0 allow, 2 block)."""
        if _bypassed():
            return 0

        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            if hook_input.get("tool_name") != "Bash":
                return 0

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0
            command = tool_input.get("command")
            if not command:
                return 0

            project_dir = get_project_directory()
            decision = evaluate_command(command, project_dir)
            if decision is None:
                # Not a gated grep, or no navigable target with an available LSP.
                return 0

            guidance = build_guidance(decision["symbols"], decision["target"])
            symbol_note = ",".join(decision["symbols"])

            if _warn_mode():
                # Advisory only: emit the guidance, never block (ADR-062 Section 6).
                print(guidance)
                print(
                    f"lsp-bash-grep-guard: warn grep symbols=[{symbol_note}] "
                    f"target={decision['target']}",
                    file=sys.stderr,
                )
                return 0

            print(guidance)
            print(
                f"lsp-bash-grep-guard: blocked grep symbols=[{symbol_note}] "
                f"target={decision['target']}",
                file=sys.stderr,
            )
            return 2

        except Exception as exc:
            # Fail-open on any error: a navigation gate degrades to allowing the
            # raw tool, never to a deadlock (ADR-062 Section 5, release-it.md).
            print(f"lsp-bash-grep-guard error: {type(exc).__name__} - {exc}", file=sys.stderr)
            return 0
    return main()

_shim_dispatch()
