from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: Bash(git commit*)
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'Bash(git commit*)'


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("tool_name")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("tool_input"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read()
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Verify git branch matches session context before commit/push.

    Claude Code PreToolUse hook that intercepts git commit/push commands and
    verifies the current branch matches the expected branch from the session log.
    Prevents cross-PR contamination by catching branch mismatches.

    Root cause addressed: PR co-mingling from PR #669 retrospective.

    Hook Type: PreToolUse
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Allow (branch matches or no session context)
        2 = Block (branch mismatch detected)
    """


    import json
    import os
    import subprocess
    import sys
    from pathlib import Path

    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        # Walk up from this hook looking for .claude-plugin/plugin.json
        # (the plugin manifest marker). The sibling lib/ is the plugin's
        # lib dir. Works regardless of source vs install layout depth;
        # robust to the M5 generator copying this file to a different
        # directory level under src/<provider>/hooks/<event>/.
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print("Plugin lib directory not found", file=sys.stderr)
        sys.exit(0)  # Fail open on config issues
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import (  # noqa: E402
        get_project_directory,
        get_today_session_log,
        is_git_commit_or_push_command,
    )


    def get_current_branch(cwd: str) -> str | None:
        """Get the current git branch name."""
        try:
            result = subprocess.run(
                ["git", "branch", "--show-current"],
                capture_output=True,
                text=True,
                cwd=cwd,
                timeout=10,
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            pass
        return None


    def get_session_branch(session_log_path: Path) -> str | None:
        """Extract the expected branch from session log JSON."""
        try:
            content = session_log_path.read_text(encoding="utf-8")
            data = json.loads(content)
            # Session logs store branch at top level
            if isinstance(data, dict):
                return data.get("branch")
        except (json.JSONDecodeError, OSError, ValueError) as exc:
            print(
                f"branch_context_guard: Error reading session log '{session_log_path}': {exc}",
                file=sys.stderr,
            )
        return None


    def write_block_response(reason: str) -> None:
        """Write a JSON block response to stdout."""
        response = json.dumps({"decision": "block", "reason": reason})
        print(response)


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)

            tool_input = hook_input.get("tool_input")
            if not isinstance(tool_input, dict):
                return 0
            command = tool_input.get("command")
            if not command:
                return 0

            # Only check for git commit/push commands
            if not is_git_commit_or_push_command(command):
                return 0

            project_dir = get_project_directory()
            sessions_dir = os.path.join(project_dir, ".agents", "sessions")

            # Skip if no sessions directory (consumer repo)
            if not os.path.isdir(sessions_dir):
                return 0

            # Get current branch
            current_branch = get_current_branch(project_dir)
            if not current_branch:
                # Cannot determine branch, fail open
                print(
                    "branch_context_guard: Cannot determine current branch, skipping check",
                    file=sys.stderr,
                )
                return 0

            # Get session log
            session_log = get_today_session_log(sessions_dir)
            if session_log is None:
                # No session log, let session_log_guard handle this
                return 0

            # Get expected branch from session
            session_branch = get_session_branch(session_log)
            if not session_branch:
                # No branch in session log, skip check
                return 0

            # Compare branches
            if current_branch != session_branch:
                output = f"""
    ## BLOCKED: Branch Mismatch Detected

    **Current branch**: `{current_branch}`
    **Session expects**: `{session_branch}`

    ### Why This Matters
    Branch mismatch can cause cross-PR contamination. This happens when:
    - You switched branches mid-session without updating the session log
    - The session was created for a different PR
    - A previous operation left the repo on the wrong branch

    ### How to Fix

    **Option 1: Switch to the expected branch**
    ```bash
    git checkout {session_branch}
    ```

    **Option 2: Update session log to current branch**
    Edit `{session_log.name}` and set `"branch": "{current_branch}"`

    **Option 3: Start a new session**
    Run `/session-init` to create a session for the current branch.

    ### Evidence
    - Session log: `{session_log.name}`
    - Current time: now
    - Command blocked: `{command[:50] + "..." if len(command) > 50 else command}`

    ### Related
    - PR #669: Root cause analysis of branch co-mingling
    - Issue #682: This verification hook
    """
                print(output)
                write_block_response(
                    f"Branch mismatch: current='{current_branch}', session='{session_branch}'"
                )
                return 2

            return 0

        except Exception as exc:
            # Fail open on errors
            print(
                f"branch_context_guard error: {type(exc).__name__} - {exc}",
                file=sys.stderr,
            )
            return 0


    if __name__ == "__main__":
        sys.exit(main())
    return 0

_shim_dispatch()
