from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: ^(Write|Edit)$
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(Write|Edit)$'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Auto-lint markdown files after Write/Edit operations.

    Claude Code PostToolUse hook that automatically runs markdownlint-cli2 --fix
    on .md files after they are written or edited. This ensures consistent markdown
    formatting across the project without manual intervention.

    Hook Type: PostToolUse
    Matcher: Write|Edit
    Filter: .md files only
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Always (non-blocking hook, all errors are warnings)
    """


    import json
    import os
    import shutil
    import subprocess
    import sys
    from pathlib import Path


    def get_file_path_from_input(hook_input: dict[str, object]) -> str | None:
        """Extract file_path from hook input's tool_input."""
        tool_input = hook_input.get("tool_input")
        if isinstance(tool_input, dict):
            file_path = tool_input.get("file_path")
            if isinstance(file_path, str) and file_path.strip():
                return file_path.strip()
        return None


    def get_project_directory(hook_input: dict[str, object]) -> str:
        """Resolve the project directory from environment or hook input."""
        env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
        if env_dir:
            return env_dir
        cwd = hook_input.get("cwd")
        if isinstance(cwd, str) and cwd.strip():
            return cwd.strip()
        return os.getcwd()


    def should_lint_file(file_path: str | None, project_dir: str) -> bool:
        """Check if the file is a markdown file within the project that exists on disk."""
        if not file_path:
            return False
        if not file_path.lower().endswith(".md"):
            return False
        resolved = Path(file_path).resolve()
        project_resolved = Path(project_dir).resolve()
        if not str(resolved).startswith(str(project_resolved) + os.sep):
            print(
                f"WARNING: Path outside project directory: {file_path}",
                file=sys.stderr,
            )
            return False
        if not resolved.exists():
            print(
                f"WARNING: Markdown file does not exist: {file_path}",
                file=sys.stderr,
            )
            return False
        return True


    def main() -> int:
        """Main hook entry point. Returns exit code."""
        if not shutil.which("npx"):
            print("[SKIP] npx not found. Install Node.js for markdown auto-linting.", file=sys.stderr)
            return 0

        try:
            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)
        except (json.JSONDecodeError, ValueError):
            print(
                "WARNING: Markdown auto-lint: Failed to parse hook input JSON",
                file=sys.stderr,
            )
            return 0

        file_path = get_file_path_from_input(hook_input)
        project_dir = get_project_directory(hook_input)
        if not should_lint_file(file_path, project_dir) or file_path is None:
            return 0

        try:
            result = subprocess.run(
                ["npx", "markdownlint-cli2", "--fix", file_path],
                capture_output=True,
                text=True,
                cwd=project_dir,
            )

            if result.returncode != 0:
                output = (result.stderr or result.stdout or "").strip()
                if not output:
                    print(
                        f"WARNING: Markdown linting failed for {file_path} "
                        f"(exit {result.returncode}) with no output. "
                        "Linter may not be installed.",
                        file=sys.stderr,
                    )
                    print(
                        "\n**Markdown Auto-Lint WARNING**: Linter failed with no output. "
                        "Verify installation: `npm list markdownlint-cli2`\n"
                    )
                else:
                    error_summary = output[:200]
                    print(
                        f"WARNING: Markdown linting failed for {file_path} "
                        f"(exit {result.returncode}): {error_summary}",
                        file=sys.stderr,
                    )
                    print(
                        f"\n**Markdown Auto-Lint WARNING**: Failed to lint `{file_path}`. "
                        f"Exit code: {result.returncode}. "
                        f"Run manually: `npx markdownlint-cli2 --fix '{file_path}'`\n"
                    )
            else:
                print(f"\n**Markdown Auto-Lint**: Fixed formatting in `{file_path}`\n")
        except FileNotFoundError:
            print(
                f"WARNING: npx not found. Cannot lint {file_path}",
                file=sys.stderr,
            )
            print(
                "\n**Markdown Auto-Lint WARNING**: npx not found. "
                "Install Node.js and markdownlint-cli2.\n"
            )
        except OSError as exc:
            print(
                f"WARNING: Markdown auto-lint: File system error for {file_path}: {exc}",
                file=sys.stderr,
            )
            print(
                f"\n**Markdown Auto-Lint ERROR**: Cannot access file `{file_path}`. "
                "Check permissions.\n"
            )

        return 0
    return main()

_shim_dispatch()
