from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: ^(Write|Edit)$
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(Write|Edit)$'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Detect ADR file changes and inject /adr-review guidance.

    Claude Code PostToolUse hook that fires after Write, Edit, or Bash
    operations targeting ADR files. Injects context reminding Claude that
    /adr-review is required before committing ADR changes.

    This is shift-left from the commit-time gate (invoke_adr_review_guard.py).
    Guidance is injected immediately when an ADR is created, modified, or deleted,
    not deferred until commit.

    Detected operations:
    - Write: New ADR file created or overwritten
    - Edit: Existing ADR file modified
    - Bash: rm, git rm, mv, git mv targeting ADR files

    Hook Type: PostToolUse
    Exit Codes:
        0 = Always (non-blocking, injects guidance via stdout)
    """


    import json
    import os
    import re
    import sys
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):
        print(f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})", file=sys.stderr)
        sys.exit(2)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402

    _ADR_PATH_PATTERN = re.compile(r"ADR-\d+.*\.md$", re.IGNORECASE)
    _CANONICAL_SOURCE_PATTERN = re.compile(r"SESSION-PROTOCOL\.md$", re.IGNORECASE)

    # Bash commands that remove or rename files
    _DESTRUCTIVE_CMD_PATTERN = re.compile(
        r"\b(?:rm|git\s+rm|mv|git\s+mv)\b.*(?:ADR-\d+.*\.md|SESSION-PROTOCOL\.md)",
        re.IGNORECASE,
    )

    _GUIDANCE_CREATE = """\

    ## ADR Change Detected: File Created

    **{file_path}** was just created.

    Before committing, you MUST run `/adr-review` for multi-agent consensus.
    The commit-time gate will block without review evidence.
    """

    _GUIDANCE_EDIT = """\

    ## ADR Change Detected: File Modified

    **{file_path}** was just modified.

    Before committing, you MUST run `/adr-review` for multi-agent consensus.
    The commit-time gate will block without review evidence.
    """

    _GUIDANCE_DELETE = """\

    ## ADR Change Detected: File Removed

    An ADR file was targeted by a destructive operation: `{command}`

    Before committing, you MUST run `/adr-review` to document the deprecation.
    The commit-time gate will block without review evidence.
    """


    def _is_adr_path(file_path: str) -> bool:
        """Check if a file path targets an ADR or canonical source file."""
        return bool(
            _ADR_PATH_PATTERN.search(file_path)
            or _CANONICAL_SOURCE_PATTERN.search(file_path)
        )


    def _detect_adr_in_bash(command: str) -> bool:
        """Check if a bash command performs a destructive operation on an ADR file."""
        return bool(_DESTRUCTIVE_CMD_PATTERN.search(command))


    def _detect_write_or_edit(tool_input: dict[str, object]) -> str | None:
        """Detect Write or Edit targeting an ADR file. Returns the file path or None."""
        file_path = str(tool_input.get("file_path", ""))
        if not file_path:
            return None
        if _is_adr_path(file_path):
            return file_path
        return None


    def main() -> int:
        """Main hook entry point."""
        if skip_if_consumer_repo("adr-lifecycle-hook"):
            return 0

        raw = ""
        try:
            if sys.stdin.isatty():
                return 0

            raw = sys.stdin.read()
            if not raw.strip():
                return 0

            hook_input = json.loads(raw)
            tool_name = hook_input.get("tool_name", "")
            tool_input = hook_input.get("tool_input", {})

            if not isinstance(tool_input, dict):
                return 0

            if tool_name in ("Write", "Edit"):
                adr_path = _detect_write_or_edit(tool_input)
                if adr_path:
                    # Write = new file or full replacement, Edit = modification
                    is_new = tool_name == "Write"
                    if is_new:
                        print(_GUIDANCE_CREATE.format(file_path=adr_path))
                    else:
                        print(_GUIDANCE_EDIT.format(file_path=adr_path))

            elif tool_name == "Bash":
                command = str(tool_input.get("command", ""))
                if command and _detect_adr_in_bash(command):
                    print(_GUIDANCE_DELETE.format(command=command))

        except Exception as exc:
            # Fail-open: never block on infrastructure errors
            input_size = len(raw) if raw else 0
            print(f"ADR lifecycle hook error (input_size={input_size}): {exc}", file=sys.stderr)

        return 0
    return main()

_shim_dispatch()
