from __future__ import annotations

# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: ^(mcp__serena__(find_symbol|find_referencing_symbols|get_symbols_overview|find_implementations|get_diagnostics_for_file)|mcp__plugin_[^_]*serena[^_]*__(find_symbol|find_referencing_symbols|get_symbols_overview|find_implementations|get_diagnostics_for_file)|LSP)$
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = '^(mcp__serena__(find_symbol|find_referencing_symbols|get_symbols_overview|find_implementations|get_diagnostics_for_file)|mcp__plugin_[^_]*serena[^_]*__(find_symbol|find_referencing_symbols|get_symbols_overview|find_implementations|get_diagnostics_for_file)|LSP)$'

# Cap stdin read so a malicious or buggy upstream cannot OOM the shim
# (CWE-400). Mirrors push_guard_base.MAX_STDIN_BYTES (1 MiB) with a
# small headroom; real Claude/Copilot tool_input commands are well
# below this limit. The cap belongs at the SHIM layer because the
# shim reads stdin BEFORE delegating to the wrapped script. Without
# it, the wrapped script's own cap is applied too late: the OOM has
# already happened.
_SHIM_MAX_STDIN_BYTES = 2 * 1024 * 1024


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize tool_input for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    # Support both VS Code-compatible snake_case (PascalCase event names)
    # and native camelCase (camelCase event names) payloads.
    # Copilot CLI sends snake_case when the event key is PascalCase,
    # camelCase when the event key is camelCase. See issue #2290.
    tool_name = payload.get("tool_name")
    if tool_name is None:
        tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `tool_name`/`toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        tool_args = payload.get("tool_input")
        if tool_args is None:
            tool_args = payload.get("toolArgs")
        # camelCase payloads send toolArgs as a JSON string, not a parsed
        # object. Parse it so _shim_normalize_args can extract "command".
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError as exc:
                # Host sent a string that is not valid JSON. Log so
                # the operator can diagnose; fall through to normalize
                # which treats raw strings as-is (glob may not match).
                print(
                    "matcher-shim [{}]: toolArgs is not valid JSON: {}".format(
                        _MATCHER, exc
                    ),
                    file=_sys.stderr,
                )
        norm_args = _shim_normalize_args(tool_args)
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_replay_bytes(payload, raw):
    replay = dict(payload)
    changed = False
    tool_name = replay.get("tool_name")
    if tool_name is None and isinstance(replay.get("toolName"), str):
        replay["tool_name"] = replay["toolName"]
        changed = True
    tool_input = replay.get("tool_input")
    if tool_input is None and "toolArgs" in replay:
        tool_args = replay.get("toolArgs")
        if isinstance(tool_args, str):
            try:
                tool_args = _json.loads(tool_args)
            except ValueError:
                pass
        replay["tool_input"] = tool_args
        changed = True
    if not changed:
        return raw
    return _json.dumps(replay, separators=(",", ":")).encode("utf-8")


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read(_SHIM_MAX_STDIN_BYTES + 1)
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if len(_raw) > _SHIM_MAX_STDIN_BYTES:
        print(
            "matcher-shim [{}]: stdin exceeds {} bytes; refusing".format(
                _MATCHER, _SHIM_MAX_STDIN_BYTES
            ),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay a canonical payload into a fresh stdin so wrapped hooks enforce
    # the same schema even when the host sent the camelCase variant.
    _replay = _shim_replay_bytes(payload, _raw)
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_replay), encoding="utf-8")
    rc = _original_main(_replay)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Track LSP-provider calls; system-of-record for ADR-062 gate state.

    Claude Code PostToolUse hook ported from the claude-code-lsp-enforcement-kit
    (nesaminua, MIT, v2.3.2), file ``kit/hooks/lsp-usage-tracker.js``. When the
    tool that just ran was a Serena symbolic tool (find_symbol,
    find_referencing_symbols, get_symbols_overview, find_implementations,
    get_diagnostics_for_file, including plugin-wrapped ``mcp__plugin_*serena*__``)
    or the native LSP tool, this hook records the navigation via
    ``lsp_gate_state.record_nav``: the first qualifying call performs warmup, every
    subsequent call increments ``nav_count``. The PreToolUse Read gate only READS
    that state; this tracker is its single writer (ADR-062 Section 4).

    Hook Type: PostToolUse
    Matcher (register in settings.json / hooks.json):
        ^(mcp__serena__(find_symbol|find_referencing_symbols|get_symbols_overview|find_implementations|get_diagnostics_for_file)|mcp__plugin_[^_]*serena[^_]*__(find_symbol|find_referencing_symbols|get_symbols_overview|find_implementations|get_diagnostics_for_file)|LSP)$

    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Always. PostToolUse never blocks. ``LSP_GATE_MODE=warn`` emits the same
            guidance as an exit-0 systemMessage; default mode is ``block`` but a
            PostToolUse tracker never blocks regardless of mode (it has nothing to
            block; the PreToolUse Read gate is where the mode toggle bites).

    Fail-open (mandatory, ADR-062 Section 5): tty stdin, empty stdin, malformed
    JSON, missing field, ``tool_input`` not a dict, ``skip_if_consumer_repo`` True,
    ``SKIP_LSP_GATE=true``, a non-LSP tool, and ANY exception all return 0 without
    mutating state. The tracker never raises.

    Canonical kit tool-name match (``lib/detect-lsp-provider.js:262-274``,
    ``isLspProviderTool``), quoted character-for-character (canonical-source-mirror.md):

        function isLspProviderTool(toolName) {
          if (!toolName || typeof toolName !== 'string') return false;
          if (!toolName.startsWith('mcp__')) return false;
          for (const key of Object.keys(PROVIDERS)) {
            const token = PROVIDERS[key].matchToken;
            // Standalone form: mcp__<token>__
            if (toolName.startsWith(`mcp__${token}__`)) return true;
            // Plugin-wrapped form: mcp__plugin_<plugin>_<token>__  (cached regex)
            const pluginRegex = PLUGIN_WRAPPED_RE.get(token);
            if (pluginRegex && pluginRegex.test(toolName)) return true;
          }
          return false;
        }

    Canonical kit warmup-then-nav increment (``lsp-usage-tracker.js:91-99``):

        if (!existing.warmup_done) {
          existing.warmup_done = true;
          existing.cold_start_retries = 0;
        } else {
          existing.nav_count = (existing.nav_count || 0) + 1;
        }
        existing.timestamp = Date.now();
        existing.last_tool = toolName;

    Stricter/looser/different than canonical
    ----------------------------------------
    - DIFFERENT provider set: the kit matches ``cclsp`` and ``serena`` by
      ``matchToken``. ADR-062 binds this port to Serena's symbolic tools plus the
      native ``LSP`` tool tier. cclsp is dropped (not used here). The native LSP
      tool name has no ``mcp__`` prefix, so it is matched separately by an exact
      ``LSP`` check rather than through the kit's ``mcp__`` token scan.
    - STRICTER serena tool gate: the kit counts ANY serena tool call as navigation
      (``isLspProviderTool`` returns true for ``mcp__serena__write_memory`` too).
      This port counts only the five SYMBOLIC navigation tools (find_symbol,
      find_referencing_symbols, get_symbols_overview, find_implementations,
      get_diagnostics_for_file). A memory write or onboarding call is not LSP
      navigation and must not warm up the Read gate.
    - DROPPED cclsp cold-start hint: the kit emits a ``systemMessage`` on the cclsp
      "No Project" upstream bug (ktnyt/cclsp#43). cclsp is not used here; the hint
      is omitted. The only systemMessage this port can emit is the ``warn``-mode
      guidance.
    - DROPPED error-response gating: the kit inspects ``tool_response`` and skips
      recording on an error (``isAnyError``). This repo's shared state lib treats a
      recorded nav purely as "a symbolic tool was invoked"; the PreToolUse gate
      fail-opens, so over-counting a failed nav only relaxes the gate, never wedges
      it. Recording is unconditional on a matched tool name, matching the ADR-062
      single-system-of-record intent. Documented divergence, not an oversight.
    - DROPPED md5/24h-expiry/~/.claude state: handled in ``lsp_gate_state`` (see
      that module's divergence section); this hook only calls ``record_nav``.
    """


    import json
    import os
    import re
    import sys
    from pathlib import Path

    # Bootstrap: find lib directory via env var or manifest walk-up.
    # CLAUDE_PLUGIN_ROOT honored when set; otherwise walk up from __file__
    # looking for .claude-plugin/plugin.json (the plugin marker). Sibling
    # lib/ is the plugin's lib dir. Layout-independent: works in source
    # tree (.claude/) and in the deeper src/<provider>/hooks/<event>/ copy.
    # pragma: no cover lines below mark the env-conditional bootstrap branches.
    # They run once at import in a real harness and are exercised by the
    # subprocess entry-point tests (test_bootstrap_missing_lib_exits_0 and the
    # CLAUDE_PLUGIN_ROOT subprocess case), but those subprocesses use a separate
    # Python that does not aggregate into in-process coverage in this environment.
    # The in-process import always takes the walk-up else branch (which is
    # measured) because pytest runs with CLAUDE_PLUGIN_ROOT unset.
    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:  # pragma: no cover - harness-set env path; covered via subprocess
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _cur = Path(__file__).resolve().parent
        _lib_dir = None
        while True:
            if (_cur / ".claude-plugin" / "plugin.json").is_file():
                _lib_dir = str(_cur / "lib")
                break
            if _cur.parent == _cur:  # pragma: no cover - filesystem-root sentinel
                break
            _cur = _cur.parent
    if _lib_dir is None or not os.path.isdir(_lib_dir):  # pragma: no cover - covered via subprocess
        print(
            f"Plugin lib directory not found: {_lib_dir} (CLAUDE_PLUGIN_ROOT={_plugin_root!r})",
            file=sys.stderr,
        )
        # PostToolUse never blocks: exit 0 on bootstrap failure (fail-open).
        sys.exit(0)
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities import get_project_directory  # noqa: E402
    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402
    from hook_utilities.lsp_gate_state import record_nav  # noqa: E402
    from hook_utilities.lsp_provider import PROVIDERS  # noqa: E402

    # Serena symbolic navigation tools (ADR-062). Only these five count as LSP
    # navigation; mcp__serena__write_memory / onboarding / etc. do not warm the
    # Read gate. Derived from PROVIDERS['serena']['tools'] plus get_symbols_overview.
    _SERENA_SYMBOLIC_TOOLS: frozenset[str] = frozenset(
        {
            "find_symbol",
            "find_referencing_symbols",
            "get_symbols_overview",
            "find_implementations",
            "get_diagnostics_for_file",
        }
    )

    # Standalone serena tool: mcp__serena__<symbolic_tool>.
    _SERENA_STANDALONE = re.compile(
        r"^mcp__serena__(?P<tool>[A-Za-z0-9_]+)$"
    )
    # Plugin-wrapped serena tool: mcp__plugin_<...serena...>__<symbolic_tool>.
    # The kit uses ^mcp__plugin_[^_]+_serena__; ADR-062 widens to any plugin
    # segment containing 'serena' so context-mode-style plugin names that wrap
    # serena still match (token-anywhere, not single-segment).
    _SERENA_PLUGIN_WRAPPED = re.compile(
        r"^mcp__plugin_[^_]*serena[^_]*__(?P<tool>[A-Za-z0-9_]+)$",
        re.IGNORECASE,
    )

    # Native LSP tool: the Claude built-in 'LSP' tool (no mcp__ prefix). The
    # native_lsp provider's match_token is 'LSP' (PROVIDERS['native_lsp']).
    _NATIVE_LSP_TOOL = PROVIDERS["native_lsp"]["match_token"]


    def is_lsp_navigation_tool(tool_name: str) -> bool:
        """Return True if ``tool_name`` is a counted LSP navigation tool.

        Counts the five Serena symbolic tools (standalone or plugin-wrapped) and the
        native LSP tool. Non-symbolic serena tools (write_memory, onboarding) and
        any other tool return False (stricter than the kit; see module docstring).
        """
        if not tool_name or not isinstance(tool_name, str):
            return False
        if tool_name == _NATIVE_LSP_TOOL:
            return True
        match = _SERENA_STANDALONE.match(tool_name) or _SERENA_PLUGIN_WRAPPED.match(
            tool_name
        )
        if match is None:
            return False
        return match.group("tool") in _SERENA_SYMBOLIC_TOOLS


    def _gate_mode() -> str:
        """Return the LSP gate mode: 'warn' or 'block' (default)."""
        return "warn" if os.environ.get("LSP_GATE_MODE", "").strip() == "warn" else "block"


    def _emit_warn_message(tool_name: str, state: dict) -> None:
        """Emit the warn-mode guidance as an exit-0 systemMessage.

        In ``LSP_GATE_MODE=warn`` the tracker still records navigation but also
        surfaces the recorded progress so the operator can see the gate warming up
        without any blocking. One structured JSON line on stdout; no secrets.
        """
        nav_count = state.get("nav_count", 0)
        message = (
            f"LSP usage tracked ({tool_name}): "
            f"warmup_done={state.get('warmup_done', False)}, nav_count={nav_count}. "
            "LSP_GATE_MODE=warn: advisory only, Read gate will not block."
        )
        print(json.dumps({"systemMessage": message}))


    def main() -> int:
        """Main hook entry point. Returns exit code (always 0; PostToolUse)."""
        if skip_if_consumer_repo("lsp-usage-tracker"):
            return 0

        try:
            if os.environ.get("SKIP_LSP_GATE", "").strip().lower() == "true":
                return 0

            if sys.stdin.isatty():
                return 0

            input_json = sys.stdin.read()
            if not input_json.strip():
                return 0

            hook_input = json.loads(input_json)
            if not isinstance(hook_input, dict):
                return 0

            tool_name = hook_input.get("tool_name")
            if not isinstance(tool_name, str) or not is_lsp_navigation_tool(tool_name):
                return 0

            project_dir = get_project_directory()
            state = record_nav(project_dir)

            if _gate_mode() == "warn":
                _emit_warn_message(tool_name, state)

            print(
                f"LSP usage tracked: tool={tool_name} "
                f"warmup_done={state.get('warmup_done')} "
                f"nav_count={state.get('nav_count')}",
                file=sys.stderr,
            )
            return 0

        except Exception as exc:  # noqa: BLE001 - fail-open is mandatory
            # Fail-open on errors: a tracker failure must never block the agent.
            print(
                f"LSP usage tracker error: {type(exc).__name__} - {exc}",
                file=sys.stderr,
            )
            return 0
    return main()

_shim_dispatch()
