# AUTO-GENERATED MATCHER SHIM (REQ-003-007)
# Matcher: mcp__serena__write_memory
# Generated by build/scripts/generate_hooks.py (REQ-003-007).
# DO NOT EDIT BY HAND - regenerated on every build. Apply NO-REGEN
# sentinel ("# NO-REGEN" or sidecar .noregen) to opt out.
import os as _os
import sys as _sys
import io as _io
import json as _json
import re as _re
import fnmatch as _fnmatch

_MATCHER = 'mcp__serena__write_memory'


def _shim_classify(pattern):
    # MIRROR: classify_matcher (build-time, build/scripts/generate_hooks.py)
    # and _shim_classify (runtime, this inlined copy) MUST agree on the
    # grammar. Update both when the grammar changes.
    if pattern.startswith("^") and pattern.endswith("$"):
        return "regex", {"pattern": pattern}
    m = _re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\((.*)\)$", pattern)
    if m:
        return "tool-glob", {"toolName": m.group(1), "argsGlob": m.group(2)}
    return "bare", {"toolName": pattern}


def _shim_normalize_args(tool_args):
    r"""Stringify and whitespace-normalize toolArgs for fnmatch comparison.

    REQ-003-007: collapse \s+ to a single space and strip ends. Pattern
    is NOT normalized; authors write patterns assuming single spaces.
    """
    if isinstance(tool_args, dict):
        # Bash hooks place command under "command"; keep this fallback
        # path narrow but correct for the live corpus.
        cmd = tool_args.get("command")
        if isinstance(cmd, str):
            text = cmd
        else:
            text = _json.dumps(tool_args, sort_keys=True)
    elif isinstance(tool_args, str):
        text = tool_args
    elif tool_args is None:
        text = ""
    else:
        text = str(tool_args)
    return _re.sub(r"\s+", " ", text).strip()


def _shim_glob_match(args_glob, tool_args_norm):
    """Match args_glob against tool_args_norm with `|` as alternation.

    fnmatch treats `|` as a literal. Authors expect Claude semantics
    where each `|` branch is a separate glob alternation. Split on
    top-level `|` and OR-fold the results.
    """
    branches = args_glob.split("|") if args_glob else [""]
    for branch in branches:
        if _fnmatch.fnmatchcase(tool_args_norm, branch):
            return True
    return False


def _shim_should_fire(payload):
    kind, params = _shim_classify(_MATCHER)
    tool_name = payload.get("toolName")
    if not isinstance(tool_name, str):
        raise ValueError("hook input missing string `toolName` field")
    if kind == "regex":
        return _re.fullmatch(params["pattern"], tool_name) is not None
    if kind == "tool-glob":
        if tool_name != params["toolName"]:
            return False
        norm_args = _shim_normalize_args(payload.get("toolArgs"))
        return _shim_glob_match(params["argsGlob"], norm_args)
    # bare
    return tool_name == params["toolName"]


def _shim_dispatch():
    try:
        _raw = _sys.stdin.buffer.read()
    except Exception as exc:  # pragma: no cover - defensive
        print(
            "matcher-shim [{}]: failed to buffer stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        payload = _json.loads(_raw or b"{}")
    except _json.JSONDecodeError as exc:
        print(
            "matcher-shim [{}]: malformed JSON on stdin: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    try:
        fire = _shim_should_fire(payload)
    except Exception as exc:
        print(
            "matcher-shim [{}]: dispatch error: {}".format(_MATCHER, exc),
            file=_sys.stderr,
        )
        _sys.exit(2)
    if _os.environ.get("COPILOT_HOOK_DEBUG"):
        kind, _ = _shim_classify(_MATCHER)
        _sys.stderr.write(
            "matcher-shim [{}]: kind={} fired={}\n".format(_MATCHER, kind, fire)
        )
    if not fire:
        _sys.exit(0)
    # Replay raw bytes into a fresh stdin so the original script reads
    # exactly what the shim inspected. Replace BEFORE calling original.
    _sys.stdin = _io.TextIOWrapper(_io.BytesIO(_raw), encoding="utf-8")
    rc = _original_main(_raw)
    if rc is None:
        rc = 0
    _sys.exit(int(rc))


# END MATCHER SHIM

def _original_main(stdin_bytes):
    # original script body begins below
    #!/usr/bin/env python3
    """Sync observation memories to Forgetful after Serena write_memory.

    Claude Code PostToolUse hook that fires after mcp__serena__write_memory.
    When an observation file is written, triggers import to Forgetful for
    semantic search availability.

    Hook Type: PostToolUse
    Matcher: mcp__serena__write_memory
    Exit Codes (Claude Hook Semantics, exempt from ADR-035):
        0 = Always (non-blocking hook, all errors are warnings)
    """

    from __future__ import annotations

    import json
    import os
    import subprocess
    import sys
    from pathlib import Path

    _plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if _plugin_root:
        _lib_dir = str(Path(_plugin_root).resolve() / "lib")
    else:
        _lib_dir = str(Path(__file__).resolve().parents[2] / "lib")
    if not os.path.isdir(_lib_dir):
        print(f"Plugin lib directory not found: {_lib_dir}", file=sys.stderr)
        sys.exit(0)  # Non-blocking: fail open
    if _lib_dir not in sys.path:
        sys.path.insert(0, _lib_dir)

    from hook_utilities.guards import skip_if_consumer_repo  # noqa: E402


    def _get_repo_root() -> str:
        """Resolve the repository root from environment or git."""
        env_dir = os.environ.get("CLAUDE_PROJECT_DIR", "").strip()
        if env_dir:
            return env_dir
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            return result.stdout.strip()
        return os.getcwd()


    def _is_observation_memory(tool_input: dict[str, object]) -> str | None:
        """Check if the written memory is an observation file.

        Returns the memory name if it matches *-observations, else None.
        """
        name = tool_input.get("name", "")
        if not isinstance(name, str):
            return None
        if name.endswith("-observations"):
            return name
        # Also check the content/path for observation patterns
        content = str(tool_input.get("content", ""))
        if "observations" in name.lower() and (
            "HIGH confidence" in content
            or "MED confidence" in content
            or "LOW confidence" in content
        ):
            return name
        return None


    def _find_observation_file(repo_root: str, memory_name: str) -> Path | None:
        """Locate the observation markdown file in .serena/memories/.

        Validates that resolved paths stay within the memories directory
        to prevent path traversal (CWE-22).
        """
        memories_dir = Path(repo_root) / ".serena" / "memories"
        if not memories_dir.is_dir():
            return None
        # Reject names containing path separators or parent references
        if "/" in memory_name or "\\" in memory_name or ".." in memory_name:
            return None
        # Try exact match first
        candidate = (memories_dir / f"{memory_name}.md").resolve()
        if not candidate.is_relative_to(memories_dir.resolve()):
            return None
        if candidate.is_file():
            return candidate
        # Try glob match
        memories_resolved = memories_dir.resolve()
        for f in memories_dir.glob("*-observations.md"):
            if memory_name in f.stem:
                if not f.resolve().is_relative_to(memories_resolved):
                    continue
                return f
        return None


    def _run_import(repo_root: str, observation_file: Path) -> None:
        """Run the import script for a single observation file."""
        import_script = (
            Path(repo_root) / ".serena" / "scripts" / "import_observations_to_forgetful.py"
        )
        if not import_script.is_file():
            print(
                f"WARNING: Import script not found: {import_script}",
                file=sys.stderr,
            )
            return

        result = subprocess.run(
            [
                sys.executable,
                str(import_script),
                "--observation-file",
                str(observation_file),
                "--confidence-levels",
                "HIGH",
                "MED",
            ],
            capture_output=True,
            text=True,
            check=False,
            timeout=30,
            cwd=repo_root,
        )
        if result.returncode == 0:
            print(f"Observation sync complete: {observation_file.name}")
            if result.stdout.strip():
                # Show summary line only
                for line in result.stdout.strip().splitlines():
                    if line.startswith("Imported:") or line.startswith("Total learnings:"):
                        print(f"  {line.strip()}")
        else:
            print(
                f"WARNING: Observation sync failed for {observation_file.name}: "
                f"{result.stderr.strip()[:200]}",
                file=sys.stderr,
            )


    def main() -> int:
        """Main hook entry point."""
        if skip_if_consumer_repo("observation-sync"):
            return 0

        raw = ""
        try:
            if sys.stdin.isatty():
                return 0

            raw = sys.stdin.read()
            if not raw.strip():
                return 0

            hook_input = json.loads(raw)
            tool_input = hook_input.get("tool_input", {})

            if not isinstance(tool_input, dict):
                return 0

            memory_name = _is_observation_memory(tool_input)
            if not memory_name:
                return 0

            repo_root = _get_repo_root()
            observation_file = _find_observation_file(repo_root, memory_name)
            if not observation_file:
                print(
                    f"WARNING: Observation file not found for memory '{memory_name}'",
                    file=sys.stderr,
                )
                return 0

            _run_import(repo_root, observation_file)

        except Exception as exc:
            input_size = len(raw) if raw else 0
            print(
                f"Observation sync hook error (input_size={input_size}): {exc}",
                file=sys.stderr,
            )

        return 0


    if __name__ == "__main__":
        sys.exit(main())
    return 0

_shim_dispatch()
